Repository OCA/contract, pull requests merged in 2019-04, with the labels that each got.

#301 [ADD] [MIG] agreement_legal migration
  agreement_legal/README.rst
  agreement_legal/__init__.py
  agreement_legal/__manifest__.py
  agreement_legal/data/agreement_stage.xml
  agreement_legal/data/agreement_type.xml
  agreement_legal/data/ir_sequence.xml
  agreement_legal/data/module_category.xml
  agreement_legal/i18n/agreement_legal.pot
  agreement_legal/i18n/fr.po
  agreement_legal/models/__init__.py
  agreement_legal/models/agreement.py
  agreement_legal/models/agreement_appendix.py
  agreement_legal/models/agreement_clause.py
  agreement_legal/models/agreement_increasetype.py
  agreement_legal/models/agreement_line.py
  agreement_legal/models/agreement_recital.py
  agreement_legal/models/agreement_renewaltype.py
  agreement_legal/models/agreement_section.py
  agreement_legal/models/agreement_stage.py
  agreement_legal/models/agreement_status.py
  agreement_legal/models/agreement_subtype.py
  agreement_legal/models/agreement_type.py
  agreement_legal/models/product_template.py
  agreement_legal/models/res_config_settings.py
  agreement_legal/models/res_partner.py
  agreement_legal/readme/CONFIGURE.rst
  agreement_legal/readme/CONTRIBUTORS.rst
  agreement_legal/readme/CREDITS.rst
  agreement_legal/readme/DESCRIPTION.rst
  agreement_legal/readme/ROADMAP.rst
  agreement_legal/readme/USAGE.rst
  agreement_legal/report/agreement.xml
  agreement_legal/security/ir.model.access.csv
  agreement_legal/security/res_groups.xml
  agreement_legal/static/description/icon.png
  agreement_legal/static/description/index.html
  agreement_legal/views/agreement.xml
  agreement_legal/views/agreement_appendix.xml
  agreement_legal/views/agreement_clause.xml
  agreement_legal/views/agreement_increasetype.xml
  agreement_legal/views/agreement_recital.xml
  agreement_legal/views/agreement_renewaltype.xml
  agreement_legal/views/agreement_section.xml
  agreement_legal/views/agreement_stages.xml
  agreement_legal/views/agreement_subtype.xml
  agreement_legal/views/agreement_type.xml
  agreement_legal/views/menu.xml
  agreement_legal/views/res_config_settings.xml
  agreement_legal/views/res_partner.xml
Labels: approved, needs review

#303 [ADD][12.0] agreement_serviceprofile
  agreement_serviceprofile/README.rst
  agreement_serviceprofile/__init__.py
  agreement_serviceprofile/__manifest__.py
  agreement_serviceprofile/i18n/en_US.po
  agreement_serviceprofile/models/__init__.py
  agreement_serviceprofile/models/agreement_serviceprofile.py
  agreement_serviceprofile/readme/CONTRIBUTORS.rst
  agreement_serviceprofile/readme/DESCRIPTION.rst
  agreement_serviceprofile/security/ir.model.access.csv
  agreement_serviceprofile/static/description/icon.png
  agreement_serviceprofile/static/description/index.html
  agreement_serviceprofile/views/agreement_serviceprofile.xml
Labels: approved, needs review

#304 [FIX] handling code field + partner_id
  agreement_legal/models/agreement.py
  agreement_legal/views/agreement.xml
Labels: approved, needs review

#297 [MIG][12.0] agreement_repair
  agreement_repair/README.rst
  agreement_repair/__init__.py
  agreement_repair/__manifest__.py
  agreement_repair/i18n/agreement_repair.pot
  agreement_repair/i18n/de.po
  agreement_repair/models/__init__.py
  agreement_repair/models/agreement.py
  agreement_repair/models/repair.py
  agreement_repair/readme/CONTRIBUTORS.rst
  agreement_repair/readme/CREDITS.rst
  agreement_repair/readme/DESCRIPTION.rst
  agreement_repair/readme/ROADMAP.rst
  agreement_repair/readme/USAGE.rst
  agreement_repair/static/description/icon.png
  agreement_repair/static/description/index.html
  agreement_repair/views/agreement_view.xml
  agreement_repair/views/repair_view.xml
Labels: approved, needs review

#296 [MIG][12.0] agreement_stock
  agreement_stock/README.rst
  agreement_stock/__init__.py
  agreement_stock/__manifest__.py
  agreement_stock/i18n/agreement_stock.pot
  agreement_stock/i18n/de.po
  agreement_stock/models/__init__.py
  agreement_stock/models/agreement.py
  agreement_stock/models/stock.py
  agreement_stock/readme/CONTRIBUTORS.rst
  agreement_stock/readme/CREDITS.rst
  agreement_stock/readme/DESCRIPTION.rst
  agreement_stock/readme/ROADMAP.rst
  agreement_stock/readme/USAGE.rst
  agreement_stock/static/description/icon.png
  agreement_stock/static/description/index.html
  agreement_stock/views/agreement_view.xml
  agreement_stock/views/stock_view.xml
Labels: approved, needs review

#308 [FIX] agreement: Missing security rule
  agreement/models/agreement.py
  agreement/security/ir.model.access.csv
Labels: approved, needs review

#295 [MIG][12.0] agreement_mrp
  agreement_mrp/README.rst
  agreement_mrp/__init__.py
  agreement_mrp/__manifest__.py
  agreement_mrp/i18n/agreement_mrp.pot
  agreement_mrp/i18n/de.po
  agreement_mrp/models/__init__.py
  agreement_mrp/models/agreement.py
  agreement_mrp/models/mrp.py
  agreement_mrp/readme/CONTRIBUTORS.rst
  agreement_mrp/readme/CREDITS.rst
  agreement_mrp/readme/DESCRIPTION.rst
  agreement_mrp/readme/ROADMAP.rst
  agreement_mrp/readme/USAGE.rst
  agreement_mrp/static/description/icon.png
  agreement_mrp/static/description/index.html
  agreement_mrp/views/agreement_view.xml
  agreement_mrp/views/mrp_view.xml
Labels: approved, needs review

#291 [MIG][12.0] agreement_maintenance
  agreement_maintenance/README.rst
  agreement_maintenance/__init__.py
  agreement_maintenance/__manifest__.py
  agreement_maintenance/i18n/agreement_maintenance.pot
  agreement_maintenance/i18n/de.po
  agreement_maintenance/models/__init__.py
  agreement_maintenance/models/agreement.py
  agreement_maintenance/models/maintenance_request.py
  agreement_maintenance/readme/CONFIGURE.rst
  agreement_maintenance/readme/CONTRIBUTORS.rst
  agreement_maintenance/readme/CREDITS.rst
  agreement_maintenance/readme/DESCRIPTION.rst
  agreement_maintenance/readme/USAGE.rst
  agreement_maintenance/static/description/icon.png
  agreement_maintenance/static/description/index.html
  agreement_maintenance/views/agreement_view.xml
  agreement_maintenance/views/maintenance_request_view.xml
Labels: approved, needs review

#293 [FIX] agreement: Issue #290
  agreement/models/agreement.py
  agreement/models/agreement_appendix.py
  agreement/models/agreement_clause.py
  agreement/models/agreement_recital.py
  agreement/models/agreement_section.py
Labels: bug

#305 [MIG][12.0] agreement_project migration
  agreement_project/README.rst
  agreement_project/__init__.py
  agreement_project/__manifest__.py
  agreement_project/i18n/agreement_project.pot
  agreement_project/i18n/de.po
  agreement_project/i18n/fr.po
  agreement_project/models/__init__.py
  agreement_project/models/agreement.py
  agreement_project/models/project.py
  agreement_project/readme/CONTRIBUTORS.rst
  agreement_project/readme/CREDITS.rst
  agreement_project/readme/DESCRIPTION.rst
  agreement_project/readme/ROADMAP.rst
  agreement_project/readme/USAGE.rst
  agreement_project/static/description/icon.png
  agreement_project/static/description/index.html
  agreement_project/views/agreement_view.xml
  agreement_project/views/project_view.xml
Labels: needs review

#312 [12.0][IMP] agreement_legal: add custom dynamic parties
  agreement_legal/models/agreement.py
  agreement_legal/report/agreement.xml
  agreement_legal/views/agreement.xml
Labels: approved, enhancement, needs review

#294 [MIG][12.0] agreement_legal_sale
  agreement_legal_sale/README.rst
  agreement_legal_sale/__init__.py
  agreement_legal_sale/__manifest__.py
  agreement_legal_sale/i18n/agreement_sale.pot
  agreement_legal_sale/i18n/de.po
  agreement_legal_sale/models/__init__.py
  agreement_legal_sale/models/agreement.py
  agreement_legal_sale/models/product.py
  agreement_legal_sale/models/sale_order.py
  agreement_legal_sale/readme/CONFIGURE.rst
  agreement_legal_sale/readme/CONTRIBUTORS.rst
  agreement_legal_sale/readme/CREDITS.rst
  agreement_legal_sale/readme/DESCRIPTION.rst
  agreement_legal_sale/readme/ROADMAP.rst
  agreement_legal_sale/readme/USAGE.rst
  agreement_legal_sale/static/description/icon.png
  agreement_legal_sale/static/description/index.html
  agreement_legal_sale/views/agreement.xml
  agreement_legal_sale/views/product.xml
  agreement_legal_sale/views/sale_order.xml
Labels: approved, needs review

#314 [FIX][12.0] agreement_legal: Menu Icon.
  agreement_legal/views/menu.xml
Labels: approved, needs review

#317 [MIG] contract_digitized_signature: Migration to 11.0
  contract_digitized_signature/README.rst
  contract_digitized_signature/__init__.py
  contract_digitized_signature/__manifest__.py
  contract_digitized_signature/i18n/ca.po
  contract_digitized_signature/i18n/contract_digitized_signature.pot
  contract_digitized_signature/i18n/de.po
  contract_digitized_signature/i18n/el_GR.po
  contract_digitized_signature/i18n/es.po
  contract_digitized_signature/i18n/es_MX.po
  contract_digitized_signature/i18n/fi.po
  contract_digitized_signature/i18n/fr.po
  contract_digitized_signature/i18n/gl.po
  contract_digitized_signature/i18n/hi_IN.po
  contract_digitized_signature/i18n/hr.po
  contract_digitized_signature/i18n/hr_HR.po
  contract_digitized_signature/i18n/hu.po
  contract_digitized_signature/i18n/it.po
  contract_digitized_signature/i18n/nl.po
  contract_digitized_signature/i18n/pt.po
  contract_digitized_signature/i18n/pt_BR.po
  contract_digitized_signature/i18n/pt_PT.po
  contract_digitized_signature/i18n/ro.po
  contract_digitized_signature/i18n/ru.po
  contract_digitized_signature/i18n/sk_SK.po
  contract_digitized_signature/i18n/sl.po
  contract_digitized_signature/i18n/tr.po
  contract_digitized_signature/i18n/tr_TR.po
  contract_digitized_signature/i18n/zh_CN.po
  contract_digitized_signature/models/__init__.py
  contract_digitized_signature/models/account_analytic_account.py
  contract_digitized_signature/readme/CONTRIBUTORS.rst
  contract_digitized_signature/readme/DESCRIPTION.rst
  contract_digitized_signature/readme/INSTALL.rst
  contract_digitized_signature/readme/USAGE.rst
  contract_digitized_signature/report/report_contract.xml
  contract_digitized_signature/static/description/icon.png
  contract_digitized_signature/static/description/index.html
  contract_digitized_signature/tests/__init__.py
  contract_digitized_signature/tests/test_contract_tracking.py
  contract_digitized_signature/views/contract_views.xml
  oca_dependencies.txt
Labels: approved, needs review

#318 [FIX] Icon in settings
  agreement_legal/views/res_config_settings.xml
Labels: needs review
