Repository OCA/contract, pull requests merged in 2019-03, with the labels that each got.

#280 [ADD] contract_price_revision: new module to update contract prices e…
  contract_price_revision/README.rst
  contract_price_revision/__init__.py
  contract_price_revision/__manifest__.py
  contract_price_revision/i18n/contract_price_revision.pot
  contract_price_revision/i18n/es.po
  contract_price_revision/models/__init__.py
  contract_price_revision/models/account_analytic_account.py
  contract_price_revision/models/account_analytic_invoice_line.py
  contract_price_revision/readme/CONTRIBUTORS.rst
  contract_price_revision/readme/DESCRIPTION.rst
  contract_price_revision/readme/USAGE.rst
  contract_price_revision/static/description/index.html
  contract_price_revision/tests/__init__.py
  contract_price_revision/tests/test_contract_price_revision.py
  contract_price_revision/views/account_analytic_account_views.xml
  contract_price_revision/wizards/__init__.py
  contract_price_revision/wizards/create_revision_line.py
  contract_price_revision/wizards/create_revision_line_views.xml
Labels: approved, ready to merge

#286 Decimal precision in Quantity of Contract Lines
  contract/models/account_analytic_contract_line.py
Labels: approved

#287 [MIG] agreement: Migration to 12.0
  agreement/__init__.py
  agreement/__manifest__.py
  agreement/demo/demo.xml
  agreement/i18n/agreement.pot
  agreement/models/__init__.py
  agreement/models/agreement.py
  agreement/readme/CONTRIBUTORS.rst
  agreement/readme/DESCRIPTION.rst
  agreement/security/agreement_security.xml
  agreement/security/ir.model.access.csv
  agreement/views/agreement.xml
Labels: approved, needs review, ready to merge
