Repository OCA/contract, pull requests merged in 2019-12, with the labels that each got.

#433 [12.0][FIX] contract: Tests with duplicated name
  contract/tests/test_contract.py
Labels: approved

#432 [12.0][FIX] contract: Don't execute onchange after invoice creation
  contract/models/contract.py
Labels: approved

#402 [12.0][IMP] - Add contract tags
  contract/__manifest__.py
  contract/models/__init__.py
  contract/models/contract.py
  contract/models/contract_tag.py
  contract/security/contract_tag.xml
  contract/views/contract.xml
Labels: approved, needs review, ready to merge

#439 [12.0][FIX] use the new methods for next period calculation result of the refactoring in #434 to consider the recurring_invoicing_type for monthlylastday mode and clean code
  contract_forecast/models/contract_line.py
  contract_forecast/tests/test_contract_line_forecast_period.py
Labels: approved, ready to merge

#443 [FIX] agreement_legal_sale: Ensure Analytic Account is copied from SO to Agreement
  agreement_legal_sale/models/agreement.py
  agreement_legal_sale/models/sale_order.py
Labels: approved, bug, needs review
