Repository OCA/contract, pull requests merged in 2019-10, with the labels that each got.

#363 [12.0[IMP] contract add commercial partner
  contract/models/contract.py
  contract/readme/CONTRIBUTORS.rst
  contract/views/contract.xml
Labels: approved, needs review, ready to merge

#379 [IMP] Add Chatter to an Agreement Service Profile
  agreement_serviceprofile/models/agreement_serviceprofile.py
  agreement_serviceprofile/views/agreement_serviceprofile.xml
Labels: approved, ready to merge

#236 [12.0] [MIG] Contract Payment Mode
  contract_payment_mode/README.rst
  contract_payment_mode/__init__.py
  contract_payment_mode/__manifest__.py
  contract_payment_mode/hooks.py
  contract_payment_mode/i18n/ca.po
  contract_payment_mode/i18n/contract_payment_mode.pot
  contract_payment_mode/i18n/de.po
  contract_payment_mode/i18n/el_GR.po
  contract_payment_mode/i18n/es.po
  contract_payment_mode/i18n/es_MX.po
  contract_payment_mode/i18n/fi.po
  contract_payment_mode/i18n/fr.po
  contract_payment_mode/i18n/gl.po
  contract_payment_mode/i18n/hi_IN.po
  contract_payment_mode/i18n/hr.po
  contract_payment_mode/i18n/hr_HR.po
  contract_payment_mode/i18n/hu.po
  contract_payment_mode/i18n/it.po
  contract_payment_mode/i18n/nl.po
  contract_payment_mode/i18n/pt.po
  contract_payment_mode/i18n/pt_BR.po
  contract_payment_mode/i18n/pt_PT.po
  contract_payment_mode/i18n/ro.po
  contract_payment_mode/i18n/ru.po
  contract_payment_mode/i18n/sk_SK.po
  contract_payment_mode/i18n/sl.po
  contract_payment_mode/i18n/tr.po
  contract_payment_mode/i18n/tr_TR.po
  contract_payment_mode/i18n/zh_CN.po
  contract_payment_mode/models/__init__.py
  contract_payment_mode/models/contract.py
  contract_payment_mode/readme/CONFIGURE.rst
  contract_payment_mode/readme/CONTRIBUTORS.rst
  contract_payment_mode/readme/DESCRIPTION.rst
  contract_payment_mode/readme/USAGE.rst
  contract_payment_mode/static/description/index.html
  contract_payment_mode/tests/__init__.py
  contract_payment_mode/tests/test_contract_payment.py
  contract_payment_mode/views/contract_view.xml
  oca_dependencies.txt
  setup/contract_payment_mode/.eggs/README.txt
  setup/contract_payment_mode/odoo/addons/contract_payment_mode
  setup/contract_payment_mode/setup.py
Labels: approved, ready to merge

#238 [12.0] [MIG] Contract Mandate
  .travis.yml
  contract_mandate/README.rst
  contract_mandate/__init__.py
  contract_mandate/__manifest__.py
  contract_mandate/i18n/ca.po
  contract_mandate/i18n/contract_mandate.pot
  contract_mandate/i18n/de.po
  contract_mandate/i18n/el_GR.po
  contract_mandate/i18n/es.po
  contract_mandate/i18n/es_MX.po
  contract_mandate/i18n/fi.po
  contract_mandate/i18n/fr.po
  contract_mandate/i18n/gl.po
  contract_mandate/i18n/hr.po
  contract_mandate/i18n/hr_HR.po
  contract_mandate/i18n/hu.po
  contract_mandate/i18n/it.po
  contract_mandate/i18n/nl.po
  contract_mandate/i18n/pt.po
  contract_mandate/i18n/pt_BR.po
  contract_mandate/i18n/pt_PT.po
  contract_mandate/i18n/ro.po
  contract_mandate/i18n/sk_SK.po
  contract_mandate/i18n/sl.po
  contract_mandate/i18n/zh_CN.po
  contract_mandate/models/__init__.py
  contract_mandate/models/contract.py
  contract_mandate/readme/CONFIGURATION.rst
  contract_mandate/readme/CONTRIBUTORS.rst
  contract_mandate/readme/DESCRIPTION.rst
  contract_mandate/readme/USAGE.rst
  contract_mandate/static/description/index.html
  contract_mandate/tests/__init__.py
  contract_mandate/tests/test_contract_mandate.py
  contract_mandate/views/contract_view.xml
  setup/contract_mandate/.eggs/README.txt
  setup/contract_mandate/odoo/addons/contract_mandate
  setup/contract_mandate/setup.py
Labels: approved, needs review, ready to merge

#388 [FIX][12.0][Product Contract] - Remove deprecated field
  product_contract/views/sale_order.xml
Labels: approved, needs review

#390 [MIG] contract: Assign old partner's salesman to migrated contracts
  contract/migrations/12.0.4.0.0/post-migration.py
Labels: approved

#391 [12.0][FIX] contract & contract_sale - security fix
  contract/views/res_partner_view.xml
  contract_sale/__manifest__.py
  contract_sale/views/res_partner_view.xml
Labels: approved

#401 [12.0][FIX] - contract_mandate: fix inherited method call _prepare_invoice
  contract_mandate/models/contract.py
Labels: approved, needs review

#403 [12.0][IMP] - Add multi-company access rule for contract objects
  contract/security/contract_security.xml
Labels: approved, needs review

#404 [12.0][FIX] - redundant fields in contract line form view
  contract_variable_quantity/__manifest__.py
  contract_variable_quantity/views/contract_line.xml
Labels: approved, needs review

#405 [12.0][FIX] - When creating a contract from a sale order, contract company must be the same as the sale order
  contract/models/abstract_contract.py
  product_contract/models/sale_order.py
  product_contract/tests/test_sale_order.py
Labels: needs review

#406 [12.0][FIX] - Fix contract report
  contract/report/report_contract.xml
Labels: approved

#407 [12.0][FIX] - Fix performance issue on contract line read
  contract/models/contract_line.py
Labels: approved, needs review
