Repository OCA/contract, pull requests merged in 2019-05, with the labels that each got.

#319 [FIX] agreement_legal: module name
  agreement_legal/models/res_config_settings.py
  agreement_legal/views/res_config_settings.xml
Labels: bug

#330 [FIX] agreement_legal: View priority (#327)
  agreement_legal/views/agreement.xml
Labels: approved, bug

#324 [FIX] agreement_legal: Copy (#323)
  agreement/security/ir.model.access.csv
  agreement_legal/models/agreement.py
  agreement_legal/models/agreement_clause.py
  agreement_legal/models/agreement_section.py
  agreement_legal/report/agreement.xml
  agreement_legal/views/agreement.xml
Labels: approved, bug

#333 [FIX] agreement_legal: Issue #331
  agreement_legal/__init__.py
  agreement_legal/__manifest__.py
  agreement_legal/models/agreement.py
Labels: bug, needs review

#336 [IMP] agreement_legal: Add readonly group
  agreement_legal/security/ir.model.access.csv
  agreement_legal/security/res_groups.xml
  agreement_legal/views/menu.xml
Labels: approved, enhancement, needs review

#299 Update README.rst
  contract_sale/README.rst
Labels: needs fixing

#321 [10.0] [FIX] product_contract. Correctly create contract from template.
  product_contract/README.rst
  product_contract/__init__.py
  product_contract/__manifest__.py
  product_contract/models/__init__.py
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/tests/test_product_template.py
  product_contract/tests/test_sale_order.py
Labels: needs review

#204 [12.0][MIG] - Migration module contract_sale_invoicing to 12.0
  contract_sale_invoicing/README.rst
  contract_sale_invoicing/__init__.py
  contract_sale_invoicing/__manifest__.py
  contract_sale_invoicing/i18n/ca.po
  contract_sale_invoicing/i18n/contract_sale_invoicing.pot
  contract_sale_invoicing/i18n/de.po
  contract_sale_invoicing/i18n/el_GR.po
  contract_sale_invoicing/i18n/es.po
  contract_sale_invoicing/i18n/es_MX.po
  contract_sale_invoicing/i18n/fi.po
  contract_sale_invoicing/i18n/fr.po
  contract_sale_invoicing/i18n/gl.po
  contract_sale_invoicing/i18n/hi_IN.po
  contract_sale_invoicing/i18n/hr.po
  contract_sale_invoicing/i18n/hr_HR.po
  contract_sale_invoicing/i18n/hu.po
  contract_sale_invoicing/i18n/it.po
  contract_sale_invoicing/i18n/nl.po
  contract_sale_invoicing/i18n/pt.po
  contract_sale_invoicing/i18n/pt_BR.po
  contract_sale_invoicing/i18n/pt_PT.po
  contract_sale_invoicing/i18n/ro.po
  contract_sale_invoicing/i18n/sk_SK.po
  contract_sale_invoicing/i18n/sl.po
  contract_sale_invoicing/i18n/tr.po
  contract_sale_invoicing/i18n/tr_TR.po
  contract_sale_invoicing/i18n/zh.po
  contract_sale_invoicing/i18n/zh_CN.po
  contract_sale_invoicing/models/__init__.py
  contract_sale_invoicing/models/contract.py
  contract_sale_invoicing/readme/CONTRIBUTORS.rst
  contract_sale_invoicing/readme/DESCRIPTION.rst
  contract_sale_invoicing/readme/USAGE.rst
  contract_sale_invoicing/static/description/icon.png
  contract_sale_invoicing/tests/__init__.py
  contract_sale_invoicing/tests/test_contract_sale_invoicing.py
  contract_sale_invoicing/views/contract_view.xml
  setup/contract_sale_invoicing/odoo/addons/contract_sale_invoicing
  setup/contract_sale_invoicing/setup.py
Labels: approved, needs review, ready to merge

#340 [IMP] agreement_legal: Multi-level field selector
  agreement_legal/__manifest__.py
  agreement_legal/models/agreement.py
  agreement_legal/models/agreement_appendix.py
  agreement_legal/models/agreement_clause.py
  agreement_legal/models/agreement_recital.py
  agreement_legal/models/agreement_section.py
  agreement_legal/readme/USAGE.rst
  agreement_legal/report/agreement.xml
  agreement_legal/static/src/js/domain_widget_ext.js
  agreement_legal/static/src/xml/domain_widget_view.xml
  agreement_legal/views/agreement.xml
  agreement_legal/views/agreement_appendix.xml
  agreement_legal/views/agreement_clause.xml
  agreement_legal/views/agreement_recital.xml
  agreement_legal/views/agreement_section.xml
Labels: approved, enhancement, needs review

#273 [11.0][contract] fix errors in navigation to customer invoices / vendor bills
  contract/__manifest__.py
  contract/models/account_analytic_account.py
  contract/views/account_analytic_account_view.xml
  contract/views/account_invoice_view.xml
  contract/views/res_partner_view.xml
Labels: approved, needs review
