Repository OCA/contract, pull requests merged in 2019-01, with the labels that each got.

#254 [IMP] Add dynamic field editor
  agreement/models/agreement.py
  agreement/models/agreement_appendix.py
  agreement/models/agreement_clause.py
  agreement/models/agreement_recital.py
  agreement/models/agreement_section.py
  agreement/report/agreement.xml
  agreement/views/agreement.xml
  agreement/views/agreement_appendix.xml
  agreement/views/agreement_clause.xml
  agreement/views/agreement_recital.xml
  agreement/views/agreement_section.xml
  agreement/views/agreement_type.xml
Labels: approved, enhancement

#256 [FIX] agreement_sale
  agreement_sale/models/sale_order.py
  agreement_sale/views/agreement.xml
Labels: bug

#241 [FIX] Issue-199: OCA-Contract V10, if not set Partner Language so languag…
  contract/__manifest__.py
  contract/models/account_analytic_account.py
Labels: approved, ready to merge

#240 [10.0] [FIX] contract. Optimize insertion of dates in invoice and lines.
  contract/models/account_analytic_account.py
  contract/tests/test_contract.py
  contract_sale_generation/models/account_analytic_account.py
  contract_sale_generation/tests/test_contract_sale.py
Labels: approved, needs review, ready to merge

#266 [10.0][IMP] contract: Performance boost 🚀
  contract/README.rst
  contract/models/account_analytic_account.py
Labels: approved, needs review
