Repository OCA/contract, pull requests merged in 2019-06, with the labels that each got.

#337 [12.0][FIX] contract: errors in navigation to customer invoices / vendor bills
  contract/models/account_analytic_account.py
  contract/views/account_analytic_account_view.xml
  contract/views/account_invoice_view.xml
  contract/views/res_partner_view.xml
Labels: approved

#282 [10.0][IMP] contract. Enable automatic invoice generation before invoice date.
  contract/__manifest__.py
  contract/models/__init__.py
  contract/models/account_analytic_account.py
  contract/models/res_company.py
  contract/views/res_company.xml
Labels: approved, ready to merge

#348 [IMP] agreement_serviceprofile
  agreement_serviceprofile/__manifest__.py
  agreement_serviceprofile/models/__init__.py
  agreement_serviceprofile/models/agreement.py
  agreement_serviceprofile/models/agreement_serviceprofile.py
  agreement_serviceprofile/views/agreement.xml
  agreement_serviceprofile/views/agreement_serviceprofile.xml
Labels: approved, needs review
