Repository OCA/contract, pull requests merged in 2020-07, with the labels that each got.

#523 [12.0][IMP] contract: Allow to set a manual currency
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳, ready to merge

#520 [12.0] Re-introduce module agreement_account and v10 behavior
  agreement/models/agreement.py
  agreement/models/agreement_type.py
  agreement/views/agreement.xml
  agreement/views/agreement_type.xml
  agreement_account/__init__.py
  agreement_account/__manifest__.py
  agreement_account/models/__init__.py
  agreement_account/models/account_invoice.py
  agreement_account/models/agreement.py
  agreement_account/readme/CONTRIBUTORS.rst
  agreement_account/readme/DESCRIPTION.rst
  agreement_account/security/ir.model.access.csv
  agreement_account/static/description/icon.png
  agreement_account/static/description/index.html
  agreement_account/views/account_invoice.xml
  agreement_account/views/agreement.xml
  agreement_sale/__manifest__.py
  agreement_sale/models/__init__.py
  agreement_sale/models/agreement.py
  agreement_sale/models/sale.py
  agreement_sale/readme/DESCRIPTION.rst
  agreement_sale/security/ir.model.access.csv
  agreement_sale/views/agreement.xml
  agreement_sale/views/sale_order.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, question

#535 [FIX] contract: multi-company assignment notification
  contract/README.rst
  contract/models/__init__.py
  contract/models/contract.py
  contract/models/ir_ui_view.py
  contract/readme/ROADMAP.rst
  contract/static/description/index.html
Labels: approved, bot is merging ⏳

#536 [FIX] contract: return qcontext result
  contract/models/ir_ui_view.py
Labels: bot is merging ⏳
