Repository OCA/contract, pull requests merged in 2020-10, with the labels that each got.

#550 [12.0][MIG] contract_sale_generation
  contract_sale_generation/README.rst
  contract_sale_generation/__init__.py
  contract_sale_generation/__manifest__.py
  contract_sale_generation/data/contract_cron.xml
  contract_sale_generation/i18n/ca.po
  contract_sale_generation/i18n/contract_sale_generation.pot
  contract_sale_generation/i18n/de.po
  contract_sale_generation/i18n/el_GR.po
  contract_sale_generation/i18n/es.po
  contract_sale_generation/i18n/es_MX.po
  contract_sale_generation/i18n/fi.po
  contract_sale_generation/i18n/fr.po
  contract_sale_generation/i18n/gl.po
  contract_sale_generation/i18n/hi_IN.po
  contract_sale_generation/i18n/hr.po
  contract_sale_generation/i18n/hr_HR.po
  contract_sale_generation/i18n/hu.po
  contract_sale_generation/i18n/it.po
  contract_sale_generation/i18n/nl.po
  contract_sale_generation/i18n/nl_NL.po
  contract_sale_generation/i18n/pt.po
  contract_sale_generation/i18n/pt_BR.po
  contract_sale_generation/i18n/pt_PT.po
  contract_sale_generation/i18n/ro.po
  contract_sale_generation/i18n/ru.po
  contract_sale_generation/i18n/sk_SK.po
  contract_sale_generation/i18n/sl.po
  contract_sale_generation/i18n/tr.po
  contract_sale_generation/i18n/tr_TR.po
  contract_sale_generation/i18n/zh_CN.po
  contract_sale_generation/models/__init__.py
  contract_sale_generation/models/abstract_contract.py
  contract_sale_generation/models/contract.py
  contract_sale_generation/models/contract_line.py
  contract_sale_generation/models/sale_order_line.py
  contract_sale_generation/readme/CONTRIBUTORS.rst
  contract_sale_generation/readme/DESCRIPTION.rst
  contract_sale_generation/readme/USAGE.rst
  contract_sale_generation/static/description/icon.png
  contract_sale_generation/static/description/index.html
  contract_sale_generation/tests/__init__.py
  contract_sale_generation/tests/test_contract_sale.py
  contract_sale_generation/views/contract.xml
  contract_sale_generation/views/contract_template.xml
Labels: approved, bot is merging ⏳, migration, needs review

#557 [FIX] Hide create contract button as other buttons
  product_contract/views/sale_order.xml
Labels: approved, bot is merging ⏳

#560 10.0 mg contract mandate
  README.md
  contract_mandate/README.rst
  contract_mandate/__init__.py
  contract_mandate/__manifest__.py
  contract_mandate/i18n/ca.po
  contract_mandate/i18n/de.po
  contract_mandate/i18n/el_GR.po
  contract_mandate/i18n/es.po
  contract_mandate/i18n/es_MX.po
  contract_mandate/i18n/fi.po
  contract_mandate/i18n/fr.po
  contract_mandate/i18n/gl.po
  contract_mandate/i18n/hr.po
  contract_mandate/i18n/hr_HR.po
  contract_mandate/i18n/hu.po
  contract_mandate/i18n/it.po
  contract_mandate/i18n/nl.po
  contract_mandate/i18n/pt.po
  contract_mandate/i18n/pt_BR.po
  contract_mandate/i18n/pt_PT.po
  contract_mandate/i18n/ro.po
  contract_mandate/i18n/sk_SK.po
  contract_mandate/i18n/sl.po
  contract_mandate/i18n/zh_CN.po
  contract_mandate/models/__init__.py
  contract_mandate/models/contract.py
  contract_mandate/readme/CONFIGURATION.rst
  contract_mandate/readme/CONTRIBUTORS.rst
  contract_mandate/readme/DESCRIPTION.rst
  contract_mandate/readme/USAGE.rst
  contract_mandate/static/description/icon.png
  contract_mandate/static/description/index.html
  contract_mandate/tests/__init__.py
  contract_mandate/tests/test_contract_mandate.py
  contract_mandate/views/contract_view.xml
  contract_payment_auto/tests/test_account_analytic_account.py
Labels: bot is merging ⏳, migration, needs review

#558 [13.0][MIG] contract_payment_mode: Migration to 13.0
  contract_payment_mode/README.rst
  contract_payment_mode/__init__.py
  contract_payment_mode/__manifest__.py
  contract_payment_mode/hooks.py
  contract_payment_mode/i18n/ca.po
  contract_payment_mode/i18n/contract_payment_mode.pot
  contract_payment_mode/i18n/de.po
  contract_payment_mode/i18n/el_GR.po
  contract_payment_mode/i18n/es.po
  contract_payment_mode/i18n/es_MX.po
  contract_payment_mode/i18n/fi.po
  contract_payment_mode/i18n/fr.po
  contract_payment_mode/i18n/gl.po
  contract_payment_mode/i18n/hi_IN.po
  contract_payment_mode/i18n/hr.po
  contract_payment_mode/i18n/hr_HR.po
  contract_payment_mode/i18n/hu.po
  contract_payment_mode/i18n/it.po
  contract_payment_mode/i18n/nl.po
  contract_payment_mode/i18n/pt.po
  contract_payment_mode/i18n/pt_BR.po
  contract_payment_mode/i18n/pt_PT.po
  contract_payment_mode/i18n/ro.po
  contract_payment_mode/i18n/ru.po
  contract_payment_mode/i18n/sk_SK.po
  contract_payment_mode/i18n/sl.po
  contract_payment_mode/i18n/tr.po
  contract_payment_mode/i18n/tr_TR.po
  contract_payment_mode/i18n/zh_CN.po
  contract_payment_mode/models/__init__.py
  contract_payment_mode/models/contract.py
  contract_payment_mode/readme/CONFIGURE.rst
  contract_payment_mode/readme/CONTRIBUTORS.rst
  contract_payment_mode/readme/DESCRIPTION.rst
  contract_payment_mode/readme/USAGE.rst
  contract_payment_mode/static/description/icon.png
  contract_payment_mode/static/description/index.html
  contract_payment_mode/tests/__init__.py
  contract_payment_mode/tests/test_contract_payment.py
  contract_payment_mode/views/contract_view.xml
  oca_dependencies.txt
  setup/contract_payment_mode/odoo/addons/contract_payment_mode
  setup/contract_payment_mode/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#559 [13.0][MIG] contract_mandate: Migration to 13.0
  contract_mandate/README.rst
  contract_mandate/__init__.py
  contract_mandate/__manifest__.py
  contract_mandate/i18n/ca.po
  contract_mandate/i18n/contract_mandate.pot
  contract_mandate/i18n/de.po
  contract_mandate/i18n/el_GR.po
  contract_mandate/i18n/es.po
  contract_mandate/i18n/es_MX.po
  contract_mandate/i18n/fi.po
  contract_mandate/i18n/fr.po
  contract_mandate/i18n/gl.po
  contract_mandate/i18n/hr.po
  contract_mandate/i18n/hr_HR.po
  contract_mandate/i18n/hu.po
  contract_mandate/i18n/it.po
  contract_mandate/i18n/nl.po
  contract_mandate/i18n/pt.po
  contract_mandate/i18n/pt_BR.po
  contract_mandate/i18n/pt_PT.po
  contract_mandate/i18n/ro.po
  contract_mandate/i18n/sk_SK.po
  contract_mandate/i18n/sl.po
  contract_mandate/i18n/zh_CN.po
  contract_mandate/models/__init__.py
  contract_mandate/models/contract.py
  contract_mandate/readme/CONFIGURATION.rst
  contract_mandate/readme/CONTRIBUTORS.rst
  contract_mandate/readme/DESCRIPTION.rst
  contract_mandate/readme/USAGE.rst
  contract_mandate/static/description/icon.png
  contract_mandate/static/description/index.html
  contract_mandate/tests/__init__.py
  contract_mandate/tests/test_contract_mandate.py
  contract_mandate/views/contract_view.xml
  setup/contract_mandate/odoo/addons/contract_mandate
  setup/contract_mandate/setup.py
Labels: approved, bot is merging ⏳, migration, needs review
