Repository OCA/contract, pull requests merged in 2020-03, with the labels that each got.

#480 [IMP] contract: add analytic_tag_ids field in contract lines
  contract/models/contract_line.py
  contract/views/contract_line.xml
Labels: approved, needs review

#412 [12.0][ADD] - Add note field to contract
  contract/models/contract.py
  contract/report/report_contract.xml
  contract/views/contract.xml
Labels: approved, needs review, ready to merge

#479 [IMP] - Improve UX, open contract form if the sale order is related to one (same for contract)
  product_contract/models/contract.py
  product_contract/models/sale_order.py
Labels: approved, needs review, ready to merge

#465 [12.0][FIX] product_contract: set 'Contract template' field company depend
  contract_sale_mandate/tests/test_contract_sale_mandate.py
  product_contract/__manifest__.py
  product_contract/migrations/12.0.4.0.0/pre-migration.py
  product_contract/models/product_template.py
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/readme/CONTRIBUTORS.rst
  product_contract/tests/test_product.py
  product_contract/tests/test_sale_order.py
  product_contract/views/product_template.xml
  product_contract_variable_quantity/models/product_template.py
  product_contract_variable_quantity/tests/test_sale_order.py
Labels: approved, needs review, ready to merge

#481 [IMP] agreement,agreement_legal: support activities
  agreement/__manifest__.py
  agreement/models/agreement.py
  agreement/views/agreement.xml
  agreement_legal/models/agreement.py
  agreement_legal/views/agreement.xml
Labels: approved, ready to merge

#459 [12.0][IMP] - contract termination
  contract/__manifest__.py
  contract/models/__init__.py
  contract/models/contract.py
  contract/models/contract_line.py
  contract/models/contract_terminate_reason.py
  contract/security/contract_terminate_reason.xml
  contract/security/groups.xml
  contract/tests/test_contract.py
  contract/views/contract.xml
  contract/views/contract_terminate_reason.xml
  contract/wizards/__init__.py
  contract/wizards/contract_contract_terminate.py
  contract/wizards/contract_contract_terminate.xml
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/tests/test_sale_order.py
  product_contract/views/sale_order.xml
Labels: approved, needs review, ready to merge

#466 [12.0][IMP] - Improve contract "In progress" search view filter
  contract/views/contract.xml
  contract/views/res_partner_view.xml
Labels: approved, needs review, ready to merge

#471 [PRODUCT_CONTRACT] - add auto_renew_interval, auto_renew_rule_type fields to sale order line
  product_contract/models/contract_line.py
  product_contract/models/product_template.py
  product_contract/models/sale_order_line.py
  product_contract/tests/test_sale_order.py
  product_contract/views/product_template.xml
  product_contract/views/sale_order.xml
Labels: approved, needs review, ready to merge

#491 [12.0] Set company_id earlier in the invoice preparation process
  contract/models/contract.py
Labels: approved, needs review

#493 [FIX] migration from 11.0
  product_contract/migrations/12.0.3.0.0/pre-migration.py
Labels: approved, bot is merging ⏳
