Repository OCA/contract, pull requests merged in 2020-02, with the labels that each got.

#469 [FIX] contract_price_revision: do not revise lines that are not valid anymore
  contract_price_revision/wizards/create_revision_line.py
Labels: approved

#473 [12.0][FIX] agreement_legal: Change company_contact_id domain
  agreement_legal/models/agreement.py
  agreement_legal/views/agreement.xml
Labels: approved, bug, needs review

#475 [12.0][FIX] agreement_legal: Change partner_id domain in agreement view
  agreement_legal/views/agreement.xml
Labels: approved, bug, needs review

#470 [12.0][IMP] New icon for agreement modules (svg file in agreement_legal)
  agreement/static/description/icon.png
  agreement_legal/static/description/icon.png
  agreement_legal/static/description/icon.svg
  agreement_legal_sale/static/description/icon.png
  agreement_maintenance/static/description/icon.png
  agreement_mrp/static/description/icon.png
  agreement_project/static/description/icon.png
  agreement_repair/static/description/icon.png
  agreement_sale/static/description/icon.png
  agreement_serviceprofile/static/description/icon.png
  agreement_stock/static/description/icon.png
Labels: approved, enhancement, needs review, ready to merge

#457 [ADD] agreement_legal_sale_fieldservice
  agreement_legal_sale_fieldservice/README.rst
  agreement_legal_sale_fieldservice/__init__.py
  agreement_legal_sale_fieldservice/__manifest__.py
  agreement_legal_sale_fieldservice/models/__init__.py
  agreement_legal_sale_fieldservice/models/sale_order.py
  agreement_legal_sale_fieldservice/readme/CONTRIBUTORS.rst
  agreement_legal_sale_fieldservice/readme/CREDITS.rst
  agreement_legal_sale_fieldservice/readme/DESCRIPTION.rst
  agreement_legal_sale_fieldservice/readme/ROADMAP.rst
  agreement_legal_sale_fieldservice/readme/USAGE.rst
  agreement_legal_sale_fieldservice/static/description/icon.png
  agreement_legal_sale_fieldservice/static/description/index.html
  oca_dependencies.txt
Labels: enhancement, needs review
