Repository OCA/contract, pull requests merged in 2020-12, with the labels that each got.

#563 [11.0][MIG] - Migration contract_mandate
  contract_mandate/README.rst
  contract_mandate/__init__.py
  contract_mandate/__manifest__.py
  contract_mandate/i18n/ca.po
  contract_mandate/i18n/contract_mandate.pot
  contract_mandate/i18n/de.po
  contract_mandate/i18n/el_GR.po
  contract_mandate/i18n/es.po
  contract_mandate/i18n/es_MX.po
  contract_mandate/i18n/fi.po
  contract_mandate/i18n/fr.po
  contract_mandate/i18n/gl.po
  contract_mandate/i18n/hr.po
  contract_mandate/i18n/hr_HR.po
  contract_mandate/i18n/hu.po
  contract_mandate/i18n/it.po
  contract_mandate/i18n/nl.po
  contract_mandate/i18n/pt.po
  contract_mandate/i18n/pt_BR.po
  contract_mandate/i18n/pt_PT.po
  contract_mandate/i18n/ro.po
  contract_mandate/i18n/sk_SK.po
  contract_mandate/i18n/sl.po
  contract_mandate/i18n/zh_CN.po
  contract_mandate/models/__init__.py
  contract_mandate/models/contract.py
  contract_mandate/readme/CONFIGURATION.rst
  contract_mandate/readme/CONTRIBUTORS.rst
  contract_mandate/readme/DESCRIPTION.rst
  contract_mandate/readme/USAGE.rst
  contract_mandate/static/description/icon.png
  contract_mandate/static/description/index.html
  contract_mandate/tests/__init__.py
  contract_mandate/tests/test_contract_mandate.py
  contract_mandate/views/contract_view.xml
  setup/_metapackage/setup.py
  setup/contract_mandate/odoo/__init__.py
  setup/contract_mandate/odoo/addons/contract_mandate
  setup/contract_mandate/setup.cfg
  setup/contract_mandate/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#583 [12.0][IMP] contract: Add followers to invoices created
  contract/__manifest__.py
  contract/data/mail_message_subtype.xml
  contract/models/contract.py
  contract/readme/CONTRIBUTORS.rst
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳

#586 [13.0][IMP] contract: Add followers to invoices created
  contract/__manifest__.py
  contract/data/mail_message_subtype.xml
  contract/models/contract.py
  contract/readme/CONTRIBUTORS.rst
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳

#587 [12.0] [FIX] product_contract -> Expected singleton: sale.order(…, …)
  product_contract/models/sale_order.py
Labels: approved, bot is merging ⏳

#584 [12.0][IMP] contract: Portal
  contract/__init__.py
  contract/__manifest__.py
  contract/controllers/__init__.py
  contract/controllers/main.py
  contract/data/mail_template.xml
  contract/demo/assets.xml
  contract/i18n/contract.pot
  contract/i18n/es.po
  contract/models/contract.py
  contract/readme/CONFIGURE.rst
  contract/readme/DESCRIPTION.rst
  contract/readme/USAGE.rst
  contract/security/contract_security.xml
  contract/security/ir.model.access.csv
  contract/static/src/js/contract_portal_tour.js
  contract/static/src/screenshots/portal-detail.png
  contract/static/src/screenshots/portal-list.png
  contract/static/src/screenshots/portal-my.png
  contract/tests/__init__.py
  contract/tests/test_contract.py
  contract/tests/test_portal.py
  contract/views/contract.xml
  contract/views/contract_portal_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#585 [12.0][IMP] contract: Add contract modifications tracking
  contract/data/mail_message_subtype.xml
  contract/data/mail_template.xml
  contract/i18n/contract.pot
  contract/i18n/es.po
  contract/i18n/es_ES.po
  contract/models/__init__.py
  contract/models/contract.py
  contract/models/contract_modification.py
  contract/report/report_contract.xml
  contract/security/ir.model.access.csv
  contract/static/src/scss/frontend.scss
  contract/tests/test_contract.py
  contract/views/assets.xml
  contract/views/contract.xml
  contract/views/contract_portal_templates.xml
Labels: bot is merging ⏳

#593 [13.0][IMP] contract: Portal
  contract/__init__.py
  contract/__manifest__.py
  contract/controllers/__init__.py
  contract/controllers/main.py
  contract/data/mail_template.xml
  contract/models/contract.py
  contract/readme/CONFIGURE.rst
  contract/readme/DESCRIPTION.rst
  contract/readme/USAGE.rst
  contract/security/contract_security.xml
  contract/security/ir.model.access.csv
  contract/static/src/js/contract_portal_tour.js
  contract/tests/__init__.py
  contract/tests/test_contract.py
  contract/tests/test_portal.py
  contract/views/assets.xml
  contract/views/contract.xml
  contract/views/contract_portal_templates.xml
Labels: bot is merging ⏳

#594 [13.0][IMP] contract: Add contract modifications tracking
  contract/data/mail_message_subtype.xml
  contract/data/mail_template.xml
  contract/i18n/contract.pot
  contract/i18n/es.po
  contract/i18n/es_ES.po
  contract/models/__init__.py
  contract/models/contract.py
  contract/models/contract_modification.py
  contract/report/report_contract.xml
  contract/security/ir.model.access.csv
  contract/static/src/scss/frontend.scss
  contract/tests/test_contract.py
  contract/views/assets.xml
  contract/views/contract.xml
  contract/views/contract_portal_templates.xml
Labels: bot is merging ⏳

#596 [12.0][IMP] contract: Add fields to contract page in portal
  contract/i18n/contract.pot
  contract/i18n/es.po
  contract/views/contract_portal_templates.xml
Labels: approved, bot is merging ⏳
