Repository OCA/contract, pull requests merged in 2020-05, with the labels that each got.

#346 [FIX] Issue #342 [12.0][BUG] agreement_legal: new agreement button (template form)
  agreement_legal/models/agreement.py
Labels: approved, bot is merging ⏳, bug, needs review

#507 [12.0][FIX] contract: Select the correct sections/notes to be invoiced
  contract/models/abstract_contract_line.py
  contract/models/contract.py
  contract/models/contract_line.py
  contract/views/abstract_contract_line.xml
Labels: approved, bot is merging ⏳

#509 [12.0][FIX] agreement_legal
  agreement_legal/__manifest__.py
  agreement_legal/migrations/12.0.2.0.0/post-migration.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#506 [WIP][IMP] agreement: Minor improvements
  agreement/models/agreement.py
  agreement/security/ir.model.access.csv
  agreement/views/agreement.xml
Labels: approved, bot is merging ⏳, ready to merge

#387 [12.0] [ADD] Contract Variable Qty Prorated
  contract_variable_qty_prorated/README.rst
  contract_variable_qty_prorated/__init__.py
  contract_variable_qty_prorated/__manifest__.py
  contract_variable_qty_prorated/data/contract_variable_qty_prorated.xml
  contract_variable_qty_prorated/i18n/contract_variable_qty_prorated.pot
  contract_variable_qty_prorated/i18n/fr.po
  contract_variable_qty_prorated/models/__init__.py
  contract_variable_qty_prorated/models/contract_line.py
  contract_variable_qty_prorated/readme/CONTRIBUTORS.rst
  contract_variable_qty_prorated/readme/DESCRIPTION.rst
  contract_variable_qty_prorated/readme/ROADMAP.rst
  contract_variable_qty_prorated/static/description/index.html
  contract_variable_qty_prorated/tests/__init__.py
  contract_variable_qty_prorated/tests/test_compute_proprata.py
  contract_variable_qty_prorated/views/abstract_contract_view.xml
  setup/contract_variable_qty_prorated/odoo/addons/contract_variable_qty_prorated
  setup/contract_variable_qty_prorated/setup.py
Labels: bot is merging ⏳, needs review

#487 [12.0][ADD] - Add new module Contract Transmit Method
  contract_transmit_method/README.rst
  contract_transmit_method/__init__.py
  contract_transmit_method/__manifest__.py
  contract_transmit_method/models/__init__.py
  contract_transmit_method/models/contract_abstract.py
  contract_transmit_method/models/contract_contract.py
  contract_transmit_method/readme/CONTRIBUTORS.rst
  contract_transmit_method/readme/DESCRIPTION.rst
  contract_transmit_method/static/description/icon.png
  contract_transmit_method/static/description/index.html
  contract_transmit_method/tests/__init__.py
  contract_transmit_method/tests/test_contract.py
  contract_transmit_method/views/contract_contract.xml
  contract_transmit_method/views/contract_template.xml
  oca_dependencies.txt
  setup/contract_transmit_method/odoo/addons/contract_transmit_method
  setup/contract_transmit_method/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#499 [IMP] - Contract: add new recurring_rule_type quarterly and semesterly
  contract/models/abstract_contract_line.py
  contract/models/contract_line.py
  contract/tests/test_contract.py
  product_contract/models/product_template.py
  product_contract/models/sale_order_line.py
Labels: approved, bot is merging ⏳, needs review, ready to merge
