Repository OCA/contract, pull requests merged in 2020-11, with the labels that each got.

#529 [12.0][ADD] agreement_helpdesk_mgmt
  agreement_helpdesk_mgmt/README.rst
  agreement_helpdesk_mgmt/__init__.py
  agreement_helpdesk_mgmt/__manifest__.py
  agreement_helpdesk_mgmt/models/__init__.py
  agreement_helpdesk_mgmt/models/agreement.py
  agreement_helpdesk_mgmt/models/helpdesk_ticket.py
  agreement_helpdesk_mgmt/readme/CONTRIBUTORS.rst
  agreement_helpdesk_mgmt/readme/CREDITS.rst
  agreement_helpdesk_mgmt/readme/DESCRIPTION.rst
  agreement_helpdesk_mgmt/readme/USAGE.rst
  agreement_helpdesk_mgmt/static/description/banner.png
  agreement_helpdesk_mgmt/static/description/icon.png
  agreement_helpdesk_mgmt/static/description/index.html
  agreement_helpdesk_mgmt/tests/__init__.py
  agreement_helpdesk_mgmt/tests/test_agreement_helpdesk_mgmt.py
  agreement_helpdesk_mgmt/views/agreement.xml
  agreement_helpdesk_mgmt/views/helpdesk_ticket.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#556 [ADD] - add contract_queue_job and contract_invoice_auto_validate
  contract_invoice_auto_validate/README.rst
  contract_invoice_auto_validate/__init__.py
  contract_invoice_auto_validate/__manifest__.py
  contract_invoice_auto_validate/models/__init__.py
  contract_invoice_auto_validate/models/contract_contract.py
  contract_invoice_auto_validate/readme/CONTRIBUTORS.rst
  contract_invoice_auto_validate/readme/DESCRIPTION.rst
  contract_invoice_auto_validate/readme/USAGE.rst
  contract_invoice_auto_validate/static/description/icon.png
  contract_invoice_auto_validate/static/description/index.html
  contract_invoice_auto_validate/tests/__init__.py
  contract_invoice_auto_validate/tests/test_contract_invoice_auto_validate.py
  contract_queue_job/README.rst
  contract_queue_job/__init__.py
  contract_queue_job/__manifest__.py
  contract_queue_job/models/__init__.py
  contract_queue_job/models/contract_contract.py
  contract_queue_job/readme/CONTRIBUTORS.rst
  contract_queue_job/readme/DESCRIPTION.rst
  contract_queue_job/static/description/icon.png
  contract_queue_job/static/description/index.html
  contract_queue_job/tests/__init__.py
  contract_queue_job/tests/test_contract_queue_job.py
  contract_queue_job/wizards/__init__.py
  contract_queue_job/wizards/contract_manually_create_invoice.py
Labels: approved, bot is merging ⏳, needs review

#571 [13.0][FIX] contract: Only include 'section_and_note_one2many' js widget in view fields that contain it
  contract/static/src/js/section_and_note_fields_backend.js
Labels: approved, bot is merging ⏳

#555 [13.0] [MIG] contract_sale: Migration to v13.0
  contract_sale/README.rst
  contract_sale/__init__.py
  contract_sale/__manifest__.py
  contract_sale/i18n/contract_sale.pot
  contract_sale/i18n/de.po
  contract_sale/i18n/es.po
  contract_sale/i18n/es_CL.po
  contract_sale/i18n/fr.po
  contract_sale/i18n/gl.po
  contract_sale/i18n/hi_IN.po
  contract_sale/i18n/hr.po
  contract_sale/i18n/hr_HR.po
  contract_sale/i18n/it.po
  contract_sale/i18n/nl.po
  contract_sale/i18n/nl_NL.po
  contract_sale/i18n/pt.po
  contract_sale/i18n/pt_BR.po
  contract_sale/i18n/ro.po
  contract_sale/i18n/ru.po
  contract_sale/i18n/tr.po
  contract_sale/i18n/tr_TR.po
  contract_sale/i18n/zh_CN.po
  contract_sale/readme/CONTRIBUTORS.rst
  contract_sale/readme/DESCRIPTION.rst
  contract_sale/readme/USAGE.rst
  contract_sale/security/contract_security.xml
  contract_sale/security/ir.model.access.csv
  contract_sale/static/description/icon.png
  contract_sale/static/description/index.html
  contract_sale/views/abstract_contract_line.xml
  contract_sale/views/contract.xml
  contract_sale/views/contract_line.xml
  contract_sale/views/contract_template.xml
  contract_sale/views/res_partner_view.xml
  setup/contract_sale/odoo/addons/contract_sale
  setup/contract_sale/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#554 [13.0] [MIG] contract_layout_category_hide_detail: Migration to v13.0
  contract_layout_category_hide_detail/README.rst
  contract_layout_category_hide_detail/__init__.py
  contract_layout_category_hide_detail/__manifest__.py
  contract_layout_category_hide_detail/i18n/contract_layout_category_hide_detail.pot
  contract_layout_category_hide_detail/i18n/pt_BR.po
  contract_layout_category_hide_detail/models/__init__.py
  contract_layout_category_hide_detail/models/abstract_contract_line.py
  contract_layout_category_hide_detail/models/contract_line.py
  contract_layout_category_hide_detail/readme/CONTRIBUTORS.rst
  contract_layout_category_hide_detail/readme/DESCRIPTION.rst
  contract_layout_category_hide_detail/readme/ROADMAP.rst
  contract_layout_category_hide_detail/readme/USAGE.rst
  contract_layout_category_hide_detail/static/description/icon.png
  contract_layout_category_hide_detail/static/description/index.html
  contract_layout_category_hide_detail/static/description/readme-icons/eye-slash.png
  contract_layout_category_hide_detail/static/description/readme-icons/eye.png
  contract_layout_category_hide_detail/static/description/readme-icons/minus-circle.png
  contract_layout_category_hide_detail/static/description/readme-icons/plus-circle.png
  contract_layout_category_hide_detail/views/abstract_contract_line.xml
  contract_layout_category_hide_detail/views/contract.xml
  oca_dependencies.txt
  setup/contract_layout_category_hide_detail/odoo/addons/contract_layout_category_hide_detail
  setup/contract_layout_category_hide_detail/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#575 [12.0][FIX] - Fix travis
  contract_price_revision/__manifest__.py
  product_contract_variable_quantity/models/sale_order_line.py
  product_contract_variable_quantity/tests/test_sale_order.py
Labels: approved, bot is merging ⏳, needs review

#576 [11.0][FIX] - fix development_status value for contract_section module
  contract_section/__manifest__.py
Labels: bot is merging ⏳, needs review
