Repository OCA/contract, pull requests merged in 2020-01, with the labels that each got.

#452 [12.0][IMP] product_contract: set contract line analytic account at contract creation from the sale order
  product_contract/models/sale_order_line.py
Labels: approved, enhancement, needs review, ready to merge

#455 [12.0][FIX+IMP] contract: Handle properly multi-company setups
  contract/models/contract.py
  contract/models/contract_line.py
Labels: approved

#422 [12.0][FIX] - Run onchange contract_type when changing the contract template
  contract/models/contract.py
  product_contract/models/sale_order.py
Labels: approved, needs review, ready to merge

#414 [12.0][IMP] - Add an action for contracts manual invoicing
  contract/__manifest__.py
  contract/models/contract.py
  contract/tests/test_contract.py
  contract/wizards/__init__.py
  contract/wizards/contract_manually_create_invoice.py
  contract/wizards/contract_manually_create_invoice.xml
Labels: approved, needs review, ready to merge
