Repository OCA/contract, pull requests merged in 2020-08, with the labels that each got.

#537 [FIX] looping contract in recurring_create_invoice to support multi r…
  contract/models/contract.py
  contract_sale_invoicing/models/contract.py
Labels: approved, bot is merging ⏳

#441 [MIG] contract_price_revision: Migration to 12.0
  contract_price_revision/README.rst
  contract_price_revision/__init__.py
  contract_price_revision/__manifest__.py
  contract_price_revision/i18n/contract_price_revision.pot
  contract_price_revision/i18n/es.po
  contract_price_revision/migrations/12.0.1.0.0/pre-migration.py
  contract_price_revision/models/__init__.py
  contract_price_revision/models/contract_line.py
  contract_price_revision/readme/CONTRIBUTORS.rst
  contract_price_revision/readme/DESCRIPTION.rst
  contract_price_revision/readme/USAGE.rst
  contract_price_revision/static/description/icon.png
  contract_price_revision/static/description/index.html
  contract_price_revision/tests/__init__.py
  contract_price_revision/tests/test_contract_price_revision.py
  contract_price_revision/views/contract_line.xml
  contract_price_revision/wizards/__init__.py
  contract_price_revision/wizards/contract_price_revision.py
  contract_price_revision/wizards/contract_price_revision_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#540 [12.0][FIX] - fiscal position, payment mode and pricelist obtained according to contract company
  contract/models/contract.py
Labels: approved, bot is merging ⏳, needs review

#543 [IMP] agreement_serviceprofile (Copy True)
  agreement_serviceprofile/models/agreement.py
Labels: approved, bot is merging ⏳, enhancement, needs review
