Repository OCA/contract, pull requests merged in 2020-04, with the labels that each got.

#496 [FIX]contract_mandate: Search mandate from correct company if we get …
  contract_mandate/models/contract.py
Labels: bot is merging ⏳

#490 [12.0][IMP] - Add menu for contract tag
  contract/__manifest__.py
  contract/data/ir_ui_menu.xml
  contract/views/contract_tag.xml
  contract/views/contract_template.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#485 [FIX] - Group by contract template when creating contracts from SO
  product_contract/models/sale_order.py
  product_contract/tests/test_sale_order.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#497 [IMP] agreement_legal_sale: Allow Multiple SP's From SO Line
  agreement_legal_sale/__manifest__.py
  agreement_legal_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#486 [12.0][IMP] contract: add section and notes in contract line
  contract/README.rst
  contract/__manifest__.py
  contract/models/abstract_contract_line.py
  contract/models/contract_line.py
  contract/readme/ROADMAP.rst
  contract/report/report_contract.xml
  contract/static/description/index.html
  contract/static/src/js/section_and_note_fields_backend.js
  contract/tests/test_contract.py
  contract/views/abstract_contract_line.xml
  contract/views/assets.xml
  contract/views/contract.xml
  contract/views/contract_line.xml
  contract/views/contract_template.xml
  contract_sale/views/contract.xml
  contract_variable_quantity/views/abstract_contract_line.xml
  contract_variable_quantity/views/contract.xml
Labels: approved, bot is merging ⏳, ready to merge

#489 [ADD] contract_layout_category_hide_detail: new module
  contract_layout_category_hide_detail/README.rst
  contract_layout_category_hide_detail/__init__.py
  contract_layout_category_hide_detail/__manifest__.py
  contract_layout_category_hide_detail/models/__init__.py
  contract_layout_category_hide_detail/models/abstract_contract_line.py
  contract_layout_category_hide_detail/models/contract_line.py
  contract_layout_category_hide_detail/readme/CONTRIBUTORS.rst
  contract_layout_category_hide_detail/readme/DESCRIPTION.rst
  contract_layout_category_hide_detail/readme/ROADMAP.rst
  contract_layout_category_hide_detail/readme/USAGE.rst
  contract_layout_category_hide_detail/static/description/index.html
  contract_layout_category_hide_detail/static/description/readme-icons/eye-slash.png
  contract_layout_category_hide_detail/static/description/readme-icons/eye.png
  contract_layout_category_hide_detail/static/description/readme-icons/minus-circle.png
  contract_layout_category_hide_detail/static/description/readme-icons/plus-circle.png
  contract_layout_category_hide_detail/views/abstract_contract_line.xml
  contract_layout_category_hide_detail/views/contract.xml
  oca_dependencies.txt
Labels: bot is merging ⏳
