Repository OCA/contract, pull requests merged in 2021-12, with the labels that each got.

#751 [14.0][IMP] agreement_legal: agreement button
  agreement_legal/models/res_partner.py
  agreement_legal/views/res_partner.xml
Labels: approved, bot is merging ⏳

#752 [14.0][IMP] agreement_legal: Add groups in partner view.
  agreement_legal/views/res_partner.xml
Labels: bot is merging ⏳

#685 [IMP] contract_queue_job: jobify renew method for crons
  contract_queue_job/models/__init__.py
  contract_queue_job/models/contract_line.py
  contract_queue_job/tests/__init__.py
  contract_queue_job/tests/test_contract_line_queue_job.py
Labels: bot is merging ⏳

#739 [FIX]contract: Avoid error in invoicing contracts crone
  contract/models/contract.py
Labels: approved, ready to merge, bot is merging ⏳

#755 [14.0][FIX] contract: Avoid error in invoicing contracts crone (forward port)
  contract/models/contract.py
Labels: approved, bot is merging ⏳

#753 [13.0][FIX] contract: Avoid error in invoicing contracts crone (forward port)
  contract/models/contract.py
Labels: approved, bot is merging ⏳

#756 [15.0][FIX] contract: Avoid error in invoicing contracts crone (forward port)
  contract/models/contract.py
Labels: bot is merging ⏳

#703 [14.0][MIG] agreement_repair
  agreement_repair/README.rst
  agreement_repair/__init__.py
  agreement_repair/__manifest__.py
  agreement_repair/i18n/agreement_repair.pot
  agreement_repair/i18n/de.po
  agreement_repair/i18n/pt.po
  agreement_repair/i18n/pt_BR.po
  agreement_repair/i18n/zh_CN.po
  agreement_repair/models/__init__.py
  agreement_repair/models/agreement.py
  agreement_repair/models/repair.py
  agreement_repair/readme/CONTRIBUTORS.rst
  agreement_repair/readme/CREDITS.rst
  agreement_repair/readme/DESCRIPTION.rst
  agreement_repair/readme/ROADMAP.rst
  agreement_repair/readme/USAGE.rst
  agreement_repair/static/description/icon.png
  agreement_repair/static/description/index.html
  agreement_repair/tests/__init__.py
  agreement_repair/tests/test_agreement_repair.py
  agreement_repair/views/agreement_view.xml
  agreement_repair/views/repair_view.xml
  setup/agreement_repair/odoo/addons/agreement_repair
  setup/agreement_repair/setup.py
Labels: approved, bot is merging ⏳
