Repository OCA/contract, pull requests merged in 2021-04, with the labels that each got.

#659 [13.0][IMP] contract: Add portal screenshots
  contract/static/src/screenshots/portal-detail.png
  contract/static/src/screenshots/portal-list.png
  contract/static/src/screenshots/portal-my.png
Labels: bot is merging ⏳

#620 [13.0] [FIX] variable quantity view
  contract_variable_quantity/views/contract.xml
Labels: approved, bot is merging ⏳, ready to merge

#547 [12.0][IMP] agreement_serviceprofile: Allow Product Variant for Serviceprofile
  agreement_serviceprofile/models/agreement_serviceprofile.py
  agreement_serviceprofile/models/product.py
  agreement_serviceprofile/views/agreement.xml
  agreement_serviceprofile/views/agreement_serviceprofile.xml
  agreement_serviceprofile/views/product.xml
Labels: approved, bot is merging ⏳

#606 14.0 mig contract_sale
  contract_sale/README.rst
  contract_sale/__init__.py
  contract_sale/__manifest__.py
  contract_sale/i18n/contract_sale.pot
  contract_sale/i18n/de.po
  contract_sale/i18n/es.po
  contract_sale/i18n/es_CL.po
  contract_sale/i18n/fr.po
  contract_sale/i18n/gl.po
  contract_sale/i18n/hi_IN.po
  contract_sale/i18n/hr.po
  contract_sale/i18n/hr_HR.po
  contract_sale/i18n/it.po
  contract_sale/i18n/nl.po
  contract_sale/i18n/nl_NL.po
  contract_sale/i18n/pt.po
  contract_sale/i18n/pt_BR.po
  contract_sale/i18n/ro.po
  contract_sale/i18n/ru.po
  contract_sale/i18n/tr.po
  contract_sale/i18n/tr_TR.po
  contract_sale/i18n/zh_CN.po
  contract_sale/readme/CONTRIBUTORS.rst
  contract_sale/readme/DESCRIPTION.rst
  contract_sale/readme/USAGE.rst
  contract_sale/security/contract_security.xml
  contract_sale/security/ir.model.access.csv
  contract_sale/static/description/icon.png
  contract_sale/static/description/index.html
  contract_sale/views/abstract_contract_line.xml
  contract_sale/views/contract.xml
  contract_sale/views/contract_line.xml
  contract_sale/views/contract_template.xml
  contract_sale/views/res_partner_view.xml
  setup/contract_sale/odoo/addons/contract_sale
  setup/contract_sale/setup.py
Labels: approved, bot is merging ⏳, ready to merge
