Repository OCA/contract, pull requests merged in 2021-07, with the labels that each got.

#655 [MIG] 14.0 agreement_sale
  agreement_sale/README.rst
  agreement_sale/__init__.py
  agreement_sale/__manifest__.py
  agreement_sale/i18n/agreement_sale.pot
  agreement_sale/i18n/zh_CN.po
  agreement_sale/models/__init__.py
  agreement_sale/models/res_config_settings.py
  agreement_sale/models/sale.py
  agreement_sale/readme/CONTRIBUTORS.rst
  agreement_sale/readme/DESCRIPTION.rst
  agreement_sale/readme/ROADMAP.rst
  agreement_sale/security/ir.model.access.csv
  agreement_sale/static/description/icon.png
  agreement_sale/static/description/index.html
  agreement_sale/views/agreement.xml
  agreement_sale/views/res_config_settings.xml
  agreement_sale/views/sale_order.xml
  setup/agreement_sale/odoo/addons/agreement_sale
  setup/agreement_sale/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#694 [13.0][FIX] contract: Cleanup values on line when invoicing
  contract/models/contract.py
Labels: approved, bot is merging ⏳

#696 [14.0][FIX] agreement_legal (Removed old demo file causing error)
  agreement_legal/__manifest__.py
  agreement_legal/data/demo.xml
Labels: bot is merging ⏳

#553 [12.0][MIG] contract digitized signature
  contract_digitized_signature/README.rst
  contract_digitized_signature/__init__.py
  contract_digitized_signature/__manifest__.py
  contract_digitized_signature/i18n/ca.po
  contract_digitized_signature/i18n/contract_digitized_signature.pot
  contract_digitized_signature/i18n/de.po
  contract_digitized_signature/i18n/el_GR.po
  contract_digitized_signature/i18n/es.po
  contract_digitized_signature/i18n/es_MX.po
  contract_digitized_signature/i18n/fi.po
  contract_digitized_signature/i18n/fr.po
  contract_digitized_signature/i18n/gl.po
  contract_digitized_signature/i18n/hi_IN.po
  contract_digitized_signature/i18n/hr.po
  contract_digitized_signature/i18n/hr_HR.po
  contract_digitized_signature/i18n/hu.po
  contract_digitized_signature/i18n/it.po
  contract_digitized_signature/i18n/nl.po
  contract_digitized_signature/i18n/pt.po
  contract_digitized_signature/i18n/pt_BR.po
  contract_digitized_signature/i18n/pt_PT.po
  contract_digitized_signature/i18n/ro.po
  contract_digitized_signature/i18n/ru.po
  contract_digitized_signature/i18n/sk_SK.po
  contract_digitized_signature/i18n/sl.po
  contract_digitized_signature/i18n/tr.po
  contract_digitized_signature/i18n/tr_TR.po
  contract_digitized_signature/i18n/zh_CN.po
  contract_digitized_signature/models/__init__.py
  contract_digitized_signature/models/contract.py
  contract_digitized_signature/readme/CONTRIBUTORS.rst
  contract_digitized_signature/readme/DESCRIPTION.rst
  contract_digitized_signature/readme/INSTALL.rst
  contract_digitized_signature/readme/USAGE.rst
  contract_digitized_signature/report/report_contract.xml
  contract_digitized_signature/static/description/icon.png
  contract_digitized_signature/static/description/index.html
  contract_digitized_signature/tests/__init__.py
  contract_digitized_signature/tests/test_contract_tracking.py
  contract_digitized_signature/views/contract_views.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#689 [12.0][IMP] product_contract: add pricelist_id and currency_id on contract values
  product_contract/models/sale_order.py
Labels: bot is merging ⏳

#662 [14.0][MIG] Migarted contract_payment_mode module.
  contract_payment_mode/README.rst
  contract_payment_mode/__init__.py
  contract_payment_mode/__manifest__.py
  contract_payment_mode/hooks.py
  contract_payment_mode/i18n/ca.po
  contract_payment_mode/i18n/contract_payment_mode.pot
  contract_payment_mode/i18n/de.po
  contract_payment_mode/i18n/el_GR.po
  contract_payment_mode/i18n/es.po
  contract_payment_mode/i18n/es_MX.po
  contract_payment_mode/i18n/fi.po
  contract_payment_mode/i18n/fr.po
  contract_payment_mode/i18n/gl.po
  contract_payment_mode/i18n/hi_IN.po
  contract_payment_mode/i18n/hr.po
  contract_payment_mode/i18n/hr_HR.po
  contract_payment_mode/i18n/hu.po
  contract_payment_mode/i18n/it.po
  contract_payment_mode/i18n/nl.po
  contract_payment_mode/i18n/pt.po
  contract_payment_mode/i18n/pt_BR.po
  contract_payment_mode/i18n/pt_PT.po
  contract_payment_mode/i18n/ro.po
  contract_payment_mode/i18n/ru.po
  contract_payment_mode/i18n/sk_SK.po
  contract_payment_mode/i18n/sl.po
  contract_payment_mode/i18n/tr.po
  contract_payment_mode/i18n/tr_TR.po
  contract_payment_mode/i18n/zh_CN.po
  contract_payment_mode/models/__init__.py
  contract_payment_mode/models/contract.py
  contract_payment_mode/readme/CONFIGURE.rst
  contract_payment_mode/readme/CONTRIBUTORS.rst
  contract_payment_mode/readme/DESCRIPTION.rst
  contract_payment_mode/readme/USAGE.rst
  contract_payment_mode/static/description/icon.png
  contract_payment_mode/static/description/index.html
  contract_payment_mode/tests/__init__.py
  contract_payment_mode/tests/test_contract_payment.py
  contract_payment_mode/views/contract_view.xml
  setup/contract_payment_mode/odoo/addons/contract_payment_mode
  setup/contract_payment_mode/setup.py
Labels: bot is merging ⏳

#646 [12.0][FIX] agreement_legal: Add active field on Agreement Stage
  agreement_legal/models/agreement_stage.py
  agreement_legal/views/agreement_stages.xml
Labels: bot is merging ⏳

#671 [14.0][MIG] agreement serviceprofile (Version 12.0 to 14.0)
  agreement_serviceprofile/README.rst
  agreement_serviceprofile/__init__.py
  agreement_serviceprofile/__manifest__.py
  agreement_serviceprofile/data/serviceprofile_stage.xml
  agreement_serviceprofile/i18n/agreement_serviceprofile.pot
  agreement_serviceprofile/i18n/de.po
  agreement_serviceprofile/i18n/en_US.po
  agreement_serviceprofile/i18n/es.po
  agreement_serviceprofile/i18n/fr.po
  agreement_serviceprofile/i18n/pt.po
  agreement_serviceprofile/i18n/pt_BR.po
  agreement_serviceprofile/i18n/zh_CN.po
  agreement_serviceprofile/models/__init__.py
  agreement_serviceprofile/models/agreement.py
  agreement_serviceprofile/models/agreement_serviceprofile.py
  agreement_serviceprofile/models/agreement_stage.py
  agreement_serviceprofile/models/product.py
  agreement_serviceprofile/readme/CONTRIBUTORS.rst
  agreement_serviceprofile/readme/DESCRIPTION.rst
  agreement_serviceprofile/security/ir.model.access.csv
  agreement_serviceprofile/static/description/icon.png
  agreement_serviceprofile/static/description/index.html
  agreement_serviceprofile/tests/__init__.py
  agreement_serviceprofile/tests/test_agreement_serviceprofile.py
  agreement_serviceprofile/tests/test_product.py
  agreement_serviceprofile/views/agreement.xml
  agreement_serviceprofile/views/agreement_serviceprofile.xml
  agreement_serviceprofile/views/product.xml
Labels: bot is merging ⏳

#690 [14.0][MIG] agreement_stock
  agreement_stock/README.rst
  agreement_stock/__init__.py
  agreement_stock/__manifest__.py
  agreement_stock/i18n/agreement_stock.pot
  agreement_stock/i18n/de.po
  agreement_stock/i18n/es.po
  agreement_stock/i18n/fr.po
  agreement_stock/i18n/it.po
  agreement_stock/i18n/pt.po
  agreement_stock/i18n/pt_BR.po
  agreement_stock/i18n/zh_CN.po
  agreement_stock/models/__init__.py
  agreement_stock/models/agreement.py
  agreement_stock/models/stock.py
  agreement_stock/readme/CONTRIBUTORS.rst
  agreement_stock/readme/CREDITS.rst
  agreement_stock/readme/DESCRIPTION.rst
  agreement_stock/readme/ROADMAP.rst
  agreement_stock/readme/USAGE.rst
  agreement_stock/static/description/icon.png
  agreement_stock/static/description/index.html
  agreement_stock/tests/__init__.py
  agreement_stock/tests/test_stock_agreement.py
  agreement_stock/views/agreement_view.xml
  agreement_stock/views/stock_view.xml
  setup/agreement_stock/odoo/addons/agreement_stock
  setup/agreement_stock/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#702 [IMP] contract: add kanban, calendar, graph, pivot, activity views on contract
  contract/models/contract.py
  contract/views/contract.xml
Labels: approved, bot is merging ⏳

#704 [IMP] contract: add kanban, calendar, graph, pivot, activity views on…
  contract/views/contract.xml
Labels: approved, bot is merging ⏳

#693 [14.0][mig]contract_mandate
  agreement_project/test-requirements.txt
  contract_mandate/README.rst
  contract_mandate/__init__.py
  contract_mandate/__manifest__.py
  contract_mandate/i18n/ca.po
  contract_mandate/i18n/contract_mandate.pot
  contract_mandate/i18n/de.po
  contract_mandate/i18n/el_GR.po
  contract_mandate/i18n/es.po
  contract_mandate/i18n/es_MX.po
  contract_mandate/i18n/fi.po
  contract_mandate/i18n/fr.po
  contract_mandate/i18n/gl.po
  contract_mandate/i18n/hr.po
  contract_mandate/i18n/hr_HR.po
  contract_mandate/i18n/hu.po
  contract_mandate/i18n/it.po
  contract_mandate/i18n/nl.po
  contract_mandate/i18n/pt.po
  contract_mandate/i18n/pt_BR.po
  contract_mandate/i18n/pt_PT.po
  contract_mandate/i18n/ro.po
  contract_mandate/i18n/sk_SK.po
  contract_mandate/i18n/sl.po
  contract_mandate/i18n/zh_CN.po
  contract_mandate/models/__init__.py
  contract_mandate/models/contract.py
  contract_mandate/readme/CONFIGURATION.rst
  contract_mandate/readme/CONTRIBUTORS.rst
  contract_mandate/readme/DESCRIPTION.rst
  contract_mandate/readme/USAGE.rst
  contract_mandate/static/description/icon.png
  contract_mandate/static/description/index.html
  contract_mandate/tests/__init__.py
  contract_mandate/tests/test_contract_mandate.py
  contract_mandate/views/contract_view.xml
  setup/contract_mandate/odoo/addons/contract_mandate
  setup/contract_mandate/setup.py
Labels: approved, bot is merging ⏳, migration, needs review
