Repository OCA/contract, pull requests merged in 2021-03, with the labels that each got.

#544 [12.0][IMP] - use next period computed fields to init forecast
  contract_forecast/models/contract_line.py
  contract_forecast/tests/test_contract_line_forecast_period.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#398 [13.0] [MIG] agreement sale
  agreement_sale/README.rst
  agreement_sale/__init__.py
  agreement_sale/__manifest__.py
  agreement_sale/i18n/agreement_sale.pot
  agreement_sale/i18n/zh_CN.po
  agreement_sale/models/__init__.py
  agreement_sale/models/res_config_settings.py
  agreement_sale/models/sale.py
  agreement_sale/readme/CONTRIBUTORS.rst
  agreement_sale/readme/DESCRIPTION.rst
  agreement_sale/readme/ROADMAP.rst
  agreement_sale/security/ir.model.access.csv
  agreement_sale/static/description/icon.png
  agreement_sale/static/description/index.html
  agreement_sale/views/agreement.xml
  agreement_sale/views/res_config_settings.xml
  agreement_sale/views/sale_order.xml
  setup/agreement_sale/odoo/addons/agreement_sale
  setup/agreement_sale/setup.py
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#541 [12.0][IMP] - Different payment mode for contracts generated from sale orders
  contract_sale_payment_mode/__manifest__.py
  contract_sale_payment_mode/models/__init__.py
  contract_sale_payment_mode/models/res_company.py
  contract_sale_payment_mode/models/res_config_settings.py
  contract_sale_payment_mode/models/sale_order.py
  contract_sale_payment_mode/tests/test_sale_order.py
  contract_sale_payment_mode/views/res_config_settings.xml
  contract_sale_payment_mode/views/sale_order.xml
Labels: approved, bot is merging ⏳, needs review

#653 [FIX] contract: function _get_partner_contract_domain of res.partner
  contract/models/res_partner.py
Labels: approved, bot is merging ⏳

#642 [12.0][FIX] contract: consistency between contract count and contract action
  contract/models/res_partner.py
Labels: approved, bot is merging ⏳, ready to merge

#643 [FIX] agreement_helpdesk_mgmt: Remove co-author of the module.
  agreement_helpdesk_mgmt/README.rst
  agreement_helpdesk_mgmt/__manifest__.py
  agreement_helpdesk_mgmt/static/description/index.html
Labels: bot is merging ⏳

#613 [12.0][FIX] contract: Changed modification_mail auto to appear like email and not internal comment
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: bot is merging ⏳

#656 [13.0][FIX] contract: Changed modification_mail auto to appear like email and not internal comment
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳
