Repository OCA/contract, pull requests merged in 2021-09, with the labels that each got.

#714 [13.0][FIX] contract: Fix invoice creation and salesperson assignment
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳

#715 [14.0][FIX] contract: Fix invoice creation and salesperson assignment
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: bot is merging ⏳

#528 [12.0][FIX] - duplicate payement mode in supplier form views
  contract_payment_mode/views/contract_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳
