Repository OCA/contract, pull requests merged in 2021-02, with the labels that each got.

#622 [13.0][FIX] contract: Error in test_contract_invoice_followers
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳, ready to merge

#616 [12.0][FIX] contract: Incorrect product UOM qty dict key for the sale…
  contract_sale_generation/models/contract_line.py
Labels: approved, bot is merging ⏳, ready to merge

#630 [FIX] contract: remove groupby if it is in context
  contract/models/res_partner.py
Labels: bot is merging ⏳

#631 [FIX] contract: remove groupby if it is in context
  contract/models/res_partner.py
Labels: bot is merging ⏳

#628 [13.0][MIG] agreement
  agreement/README.rst
  agreement/__init__.py
  agreement/__manifest__.py
  agreement/demo/demo.xml
  agreement/i18n/agreement.pot
  agreement/i18n/ca.po
  agreement/i18n/es.po
  agreement/i18n/fr.po
  agreement/i18n/hr.po
  agreement/i18n/pt.po
  agreement/i18n/pt_BR.po
  agreement/i18n/pt_PT.po
  agreement/i18n/zh_CN.po
  agreement/migrations/13.0.1.0.0/noupdate_changes.xml
  agreement/migrations/13.0.1.0.0/post-migration.py
  agreement/models/__init__.py
  agreement/models/agreement.py
  agreement/models/agreement_type.py
  agreement/readme/CONTRIBUTORS.rst
  agreement/readme/DESCRIPTION.rst
  agreement/security/agreement_security.xml
  agreement/security/ir.model.access.csv
  agreement/static/description/icon.png
  agreement/static/description/index.html
  agreement/tests/__init__.py
  agreement/tests/test_agreement.py
  agreement/views/agreement.xml
  agreement/views/agreement_type.xml
  setup/agreement/odoo/addons/agreement
  setup/agreement/setup.py
Labels: approved, bot is merging ⏳

#621 [14.0][MIG] agreement
  agreement/README.rst
  agreement/__init__.py
  agreement/__manifest__.py
  agreement/demo/demo.xml
  agreement/i18n/agreement.pot
  agreement/i18n/ca.po
  agreement/i18n/es.po
  agreement/i18n/fr.po
  agreement/i18n/hr.po
  agreement/i18n/pt.po
  agreement/i18n/pt_BR.po
  agreement/i18n/pt_PT.po
  agreement/i18n/zh_CN.po
  agreement/models/__init__.py
  agreement/models/agreement.py
  agreement/models/agreement_type.py
  agreement/readme/CONTRIBUTORS.rst
  agreement/readme/DESCRIPTION.rst
  agreement/security/agreement_security.xml
  agreement/security/ir.model.access.csv
  agreement/static/description/icon.png
  agreement/static/description/index.html
  agreement/tests/__init__.py
  agreement/tests/test_agreement.py
  agreement/views/agreement.xml
  agreement/views/agreement_type.xml
  setup/agreement/odoo/addons/agreement
  setup/agreement/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#634 [FIX] contract: consistency between contract count and contrct action
  contract/models/res_partner.py
Labels: approved, bot is merging ⏳

#635 [FIX] contract: consistency between contract count and contract action
  contract/models/res_partner.py
Labels: bot is merging ⏳

#637 [12.0][FIX] agreement_legal: Error when mass action on list view
  agreement_legal/models/agreement.py
Labels: approved, bot is merging ⏳
