Repository OCA/contract, pull requests merged in 2021-10, with the labels that each got.

#719 [13.0][FIX] agreement_legal: Fix JS var declaration
  agreement_legal/static/src/js/domain_widget_ext.js
Labels: approved, bot is merging ⏳

#720 [13.0][FIX] agreement_legal: Remove domain from partner_id field in view.
  agreement_legal/views/agreement.xml
Labels: bot is merging ⏳

#677 [14.0][MIG] agreement_account (Version 12.0 to 14.0)
  agreement_account/README.rst
  agreement_account/__init__.py
  agreement_account/__manifest__.py
  agreement_account/i18n/agreement_account.pot
  agreement_account/models/__init__.py
  agreement_account/models/account_move.py
  agreement_account/models/agreement.py
  agreement_account/readme/CONTRIBUTORS.rst
  agreement_account/readme/DESCRIPTION.rst
  agreement_account/security/ir.model.access.csv
  agreement_account/static/description/icon.png
  agreement_account/static/description/index.html
  agreement_account/tests/__init__.py
  agreement_account/tests/test_agreement.py
  agreement_account/views/account_move.xml
  agreement_account/views/agreement.xml
Labels: approved, ready to merge, bot is merging ⏳
