Repository OCA/contract, pull requests merged in 2021-05, with the labels that each got.

#552 [12.0][IMP] - add an option to enable forecasts by company
  contract_forecast/__manifest__.py
  contract_forecast/models/__init__.py
  contract_forecast/models/contract.py
  contract_forecast/models/contract_line.py
  contract_forecast/models/res_company.py
  contract_forecast/models/res_config_settings.py
  contract_forecast/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, needs review

#674 [13.0][MIG] agreement_legal: Migration to 13.0
  agreement_legal/README.rst
  agreement_legal/__init__.py
  agreement_legal/__manifest__.py
  agreement_legal/data/agreement_stage.xml
  agreement_legal/data/agreement_type.xml
  agreement_legal/data/ir_sequence.xml
  agreement_legal/data/module_category.xml
  agreement_legal/demo/demo.xml
  agreement_legal/i18n/agreement_legal.pot
  agreement_legal/i18n/es.po
  agreement_legal/i18n/fr.po
  agreement_legal/i18n/pt.po
  agreement_legal/i18n/pt_BR.po
  agreement_legal/i18n/pt_PT.po
  agreement_legal/i18n/zh_CN.po
  agreement_legal/models/__init__.py
  agreement_legal/models/agreement.py
  agreement_legal/models/agreement_appendix.py
  agreement_legal/models/agreement_clause.py
  agreement_legal/models/agreement_increasetype.py
  agreement_legal/models/agreement_line.py
  agreement_legal/models/agreement_recital.py
  agreement_legal/models/agreement_renewaltype.py
  agreement_legal/models/agreement_section.py
  agreement_legal/models/agreement_stage.py
  agreement_legal/models/agreement_status.py
  agreement_legal/models/agreement_subtype.py
  agreement_legal/models/agreement_type.py
  agreement_legal/models/product_template.py
  agreement_legal/models/res_config_settings.py
  agreement_legal/models/res_partner.py
  agreement_legal/readme/CONFIGURE.rst
  agreement_legal/readme/CONTRIBUTORS.rst
  agreement_legal/readme/CREDITS.rst
  agreement_legal/readme/DESCRIPTION.rst
  agreement_legal/readme/ROADMAP.rst
  agreement_legal/readme/USAGE.rst
  agreement_legal/report/agreement.xml
  agreement_legal/security/ir.model.access.csv
  agreement_legal/security/res_groups.xml
  agreement_legal/static/description/icon.png
  agreement_legal/static/description/icon.svg
  agreement_legal/static/description/index.html
  agreement_legal/static/src/js/domain_widget_ext.js
  agreement_legal/static/src/xml/domain_widget_view.xml
  agreement_legal/views/agreement.xml
  agreement_legal/views/agreement_appendix.xml
  agreement_legal/views/agreement_clause.xml
  agreement_legal/views/agreement_increasetype.xml
  agreement_legal/views/agreement_recital.xml
  agreement_legal/views/agreement_renewaltype.xml
  agreement_legal/views/agreement_section.xml
  agreement_legal/views/agreement_stages.xml
  agreement_legal/views/agreement_subtype.xml
  agreement_legal/views/agreement_type.xml
  agreement_legal/views/menu.xml
  agreement_legal/views/res_config_settings.xml
  agreement_legal/views/res_partner.xml
  setup/agreement_legal/odoo/addons/agreement_legal
  setup/agreement_legal/setup.py
Labels: approved, bot is merging ⏳

#590 [12.0][REF] product_contract: micro-refactoring to ease overrides
  product_contract/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#668 [13.0][FIX] contract: Set layout for section and note in portal template
  contract/views/contract_portal_templates.xml
Labels: bot is merging ⏳

#680 [13.0][FIX] contract: Force add `access_token` in **View contract** button from contract modification mail
  contract/data/mail_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#682 [14.0][FIX-IMP] contract: Set layout for section and note in portal template + Improve code to show recurring_rule_type
  contract/views/contract_portal_templates.xml
Labels: approved, bot is merging ⏳
