Repository OCA/contract, pull requests merged in 2022-08, with the labels that each got.

#861 [14.0][IMP] contract : show tags with colors in the contract
  contract/models/contract_tag.py
  contract/views/contract.xml
  contract/views/contract_tag.xml
Labels: approved, ready to merge, bot is merging ⏳

#862 [15.0][IMP] contract : show tags with colors in the contract
  contract/models/contract_tag.py
  contract/views/contract.xml
  contract/views/contract_tag.xml
Labels: approved, ready to merge, bot is merging ⏳

#865 [13.0][FIX] agreement_rebate: Add freezegun for tests
  test-requirements.txt
Labels: bot is merging ⏳

#826 [14.0][FIX][contract] Set uom as relevant parameter to calculate price unit in automatic price mode
  contract/models/abstract_contract_line.py
  contract/tests/test_contract.py
Labels: enhancement, bot is merging ⏳

#859 [12.0][IMP] contract : show tags with colors in the contract
  contract/models/contract_tag.py
  contract/views/contract.xml
  contract/views/contract_tag.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#811 [15.0][MIG] contract_payment_mode
  contract_payment_mode/README.rst
  contract_payment_mode/__init__.py
  contract_payment_mode/__manifest__.py
  contract_payment_mode/hooks.py
  contract_payment_mode/i18n/ca.po
  contract_payment_mode/i18n/contract_payment_mode.pot
  contract_payment_mode/i18n/de.po
  contract_payment_mode/i18n/el_GR.po
  contract_payment_mode/i18n/es.po
  contract_payment_mode/i18n/es_MX.po
  contract_payment_mode/i18n/fi.po
  contract_payment_mode/i18n/fr.po
  contract_payment_mode/i18n/gl.po
  contract_payment_mode/i18n/hi_IN.po
  contract_payment_mode/i18n/hr.po
  contract_payment_mode/i18n/hr_HR.po
  contract_payment_mode/i18n/hu.po
  contract_payment_mode/i18n/it.po
  contract_payment_mode/i18n/nl.po
  contract_payment_mode/i18n/pt.po
  contract_payment_mode/i18n/pt_BR.po
  contract_payment_mode/i18n/pt_PT.po
  contract_payment_mode/i18n/ro.po
  contract_payment_mode/i18n/ru.po
  contract_payment_mode/i18n/sk_SK.po
  contract_payment_mode/i18n/sl.po
  contract_payment_mode/i18n/tr.po
  contract_payment_mode/i18n/tr_TR.po
  contract_payment_mode/i18n/zh_CN.po
  contract_payment_mode/models/__init__.py
  contract_payment_mode/models/contract.py
  contract_payment_mode/readme/CONFIGURE.rst
  contract_payment_mode/readme/CONTRIBUTORS.rst
  contract_payment_mode/readme/DESCRIPTION.rst
  contract_payment_mode/readme/USAGE.rst
  contract_payment_mode/static/description/icon.png
  contract_payment_mode/static/description/index.html
  contract_payment_mode/tests/__init__.py
  contract_payment_mode/tests/test_contract_payment.py
  contract_payment_mode/views/contract_view.xml
  setup/contract_payment_mode/odoo/addons/contract_payment_mode
  setup/contract_payment_mode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#808 [14.0][ADD] contract_delivery_zone
  contract_delivery_zone/README.rst
  contract_delivery_zone/__init__.py
  contract_delivery_zone/__manifest__.py
  contract_delivery_zone/models/__init__.py
  contract_delivery_zone/models/contract_contract.py
  contract_delivery_zone/readme/CONTRIBUTORS.rst
  contract_delivery_zone/readme/DESCRIPTION.rst
  contract_delivery_zone/static/description/icon.png
  contract_delivery_zone/static/description/index.html
  contract_delivery_zone/tests/__init__.py
  contract_delivery_zone/tests/test_contract_delivery_zone.py
  contract_delivery_zone/views/contract_contract.xml
  setup/contract_delivery_zone/odoo/addons/contract_delivery_zone
  setup/contract_delivery_zone/setup.py
Labels: bot is merging ⏳, stale

#857 [14.0][IMP] contract: Set default name to '/' for newly created invoice from contract
  contract/models/contract.py
Labels: approved, bot is merging ⏳
