Repository OCA/contract, pull requests merged in 2022-09, with the labels that each got.

#873 [14.0][IMP] contract: Use _prepare_home_portal_values() function.
  contract/controllers/main.py
  contract/views/contract_portal_templates.xml
Labels: approved, bot is merging ⏳

#874 [15.0][IMP] contract: Use _prepare_home_portal_values() function.
  contract/controllers/main.py
  contract/views/contract_portal_templates.xml
Labels: enhancement, bot is merging ⏳

#876 [FIX] contract unittest test_contract.py
  contract/tests/test_contract.py
  contract/tests/test_contract_manually_create_invoice.py
  contract/tests/test_multicompany.py
Labels: approved, ready to merge, bot is merging ⏳

#864 [13.0][MIG] contract_price_revision + improvements
  contract_price_revision/README.rst
  contract_price_revision/__init__.py
  contract_price_revision/__manifest__.py
  contract_price_revision/i18n/contract_price_revision.pot
  contract_price_revision/i18n/es.po
  contract_price_revision/models/__init__.py
  contract_price_revision/models/contract_line.py
  contract_price_revision/readme/CONTRIBUTORS.rst
  contract_price_revision/readme/DESCRIPTION.rst
  contract_price_revision/readme/USAGE.rst
  contract_price_revision/static/description/icon.png
  contract_price_revision/static/description/index.html
  contract_price_revision/tests/__init__.py
  contract_price_revision/tests/test_contract_price_revision.py
  contract_price_revision/views/contract_line.xml
  contract_price_revision/wizards/__init__.py
  contract_price_revision/wizards/contract_price_revision.py
  contract_price_revision/wizards/contract_price_revision_views.xml
  setup/contract_price_revision/odoo/addons/contract_price_revision
  setup/contract_price_revision/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#866 [IMP] contract: Add contract date
  contract/__manifest__.py
  contract/migrations/13.0.2.10.0/pre-migrate.py
  contract/models/abstract_contract.py
  contract/views/contract.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳
