Repository OCA/contract, pull requests merged in 2022-11, with the labels that each got.

#890 [15.0][DCK] Updated from template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  contract/models/contract.py
  contract/models/contract_line.py
Labels: bot is merging ⏳

#891 [15.0][FIX] contract_sale_generation: Change SavepointCase to TransactionCase
  contract_sale_generation/tests/test_contract_sale.py
  contract_sale_generation/tests/test_contract_sale_recurrency.py
Labels: bot is merging ⏳

#810 [14.0][ADD] contract_update_last_date_invoiced
  contract_update_last_date_invoiced/README.rst
  contract_update_last_date_invoiced/__init__.py
  contract_update_last_date_invoiced/__manifest__.py
  contract_update_last_date_invoiced/models/__init__.py
  contract_update_last_date_invoiced/models/contract_line.py
  contract_update_last_date_invoiced/readme/CONTRIBUTORS.rst
  contract_update_last_date_invoiced/readme/DESCRIPTION.rst
  contract_update_last_date_invoiced/readme/USAGE.rst
  contract_update_last_date_invoiced/security/security.xml
  contract_update_last_date_invoiced/static/description/icon.png
  contract_update_last_date_invoiced/static/description/index.html
  contract_update_last_date_invoiced/views/contract_line.xml
  contract_update_last_date_invoiced/wizards/__init__.py
  contract_update_last_date_invoiced/wizards/update_last_date_invoiced.py
  contract_update_last_date_invoiced/wizards/update_last_date_invoiced.xml
  setup/contract_update_last_date_invoiced/odoo/addons/contract_update_last_date_invoiced
  setup/contract_update_last_date_invoiced/setup.py
Labels: bot is merging ⏳

#893 [14.0][FIX] contract: Switch string > title in buttons
  contract/views/contract_line.xml
Labels: approved, bot is merging ⏳

#898 [UPD] Copier update
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#829 [14.0] [MIG] contract_invoice_start_end_dates
  contract_invoice_start_end_dates/README.rst
  contract_invoice_start_end_dates/__init__.py
  contract_invoice_start_end_dates/__manifest__.py
  contract_invoice_start_end_dates/i18n/contract_invoice_start_end_dates.pot
  contract_invoice_start_end_dates/i18n/da.po
  contract_invoice_start_end_dates/models/__init__.py
  contract_invoice_start_end_dates/models/contract_line.py
  contract_invoice_start_end_dates/readme/CONTRIBUTORS.rst
  contract_invoice_start_end_dates/readme/DESCRIPTION.rst
  contract_invoice_start_end_dates/static/description/icon.png
  contract_invoice_start_end_dates/static/description/index.html
  contract_invoice_start_end_dates/tests/__init__.py
  contract_invoice_start_end_dates/tests/test_contract_invoice_start_end_dates.py
  setup/contract_invoice_start_end_dates/odoo/addons/contract_invoice_start_end_dates
  setup/contract_invoice_start_end_dates/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳
