Repository OCA/contract, pull requests merged in 2022-02, with the labels that each got.

#773 [15.0 ][MIG] contract_sale
  contract_sale/README.rst
  contract_sale/__init__.py
  contract_sale/__manifest__.py
  contract_sale/i18n/contract_sale.pot
  contract_sale/i18n/de.po
  contract_sale/i18n/es.po
  contract_sale/i18n/es_AR.po
  contract_sale/i18n/es_CL.po
  contract_sale/i18n/fr.po
  contract_sale/i18n/gl.po
  contract_sale/i18n/hi_IN.po
  contract_sale/i18n/hr.po
  contract_sale/i18n/hr_HR.po
  contract_sale/i18n/it.po
  contract_sale/i18n/nl.po
  contract_sale/i18n/nl_NL.po
  contract_sale/i18n/pt.po
  contract_sale/i18n/pt_BR.po
  contract_sale/i18n/ro.po
  contract_sale/i18n/ru.po
  contract_sale/i18n/tr.po
  contract_sale/i18n/tr_TR.po
  contract_sale/i18n/zh_CN.po
  contract_sale/readme/CONTRIBUTORS.rst
  contract_sale/readme/DESCRIPTION.rst
  contract_sale/readme/USAGE.rst
  contract_sale/security/contract_security.xml
  contract_sale/security/ir.model.access.csv
  contract_sale/static/description/icon.png
  contract_sale/static/description/index.html
  contract_sale/tests/__init__.py
  contract_sale/tests/test_sale_contract.py
  contract_sale/views/abstract_contract_line.xml
  contract_sale/views/contract.xml
  contract_sale/views/contract_line.xml
  contract_sale/views/contract_template.xml
  contract_sale/views/res_partner_view.xml
  setup/contract_sale/odoo/addons/contract_sale
  setup/contract_sale/setup.py
Labels: approved, bot is merging ⏳

#775 [13.0][IMP] contract: Add discount + price_subtotal fields to the contract lines in the portal view.
  contract/views/contract_portal_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#778 [14.0][IMP] contract: Add discount + price_subtotal fields to the contract lines in the portal view.
  contract/views/contract_portal_templates.xml
Labels: approved, bot is merging ⏳

#779 [15.0][IMP] contract: Add discount + price_subtotal fields to the contract lines in the portal view.
  contract/views/contract_portal_templates.xml
Labels: approved, bot is merging ⏳

#784 [14.0][IMP] contract: remove l10n_generic_coa dependency
  contract/tests/test_multicompany.py
Labels: bot is merging ⏳

#783 ADJ: When generating invoices from the Wizard to create invoices …
  contract/tests/__init__.py
  contract/tests/test_contract.py
  contract/tests/test_contract_manually_create_invoice.py
  contract/wizards/contract_manually_create_invoice.py
Labels: approved, bot is merging ⏳

#743 [14.0][MIG] contract_sale_generation
  contract_sale_generation/README.rst
  contract_sale_generation/__init__.py
  contract_sale_generation/__manifest__.py
  contract_sale_generation/data/contract_cron.xml
  contract_sale_generation/i18n/ca.po
  contract_sale_generation/i18n/contract_sale_generation.pot
  contract_sale_generation/i18n/de.po
  contract_sale_generation/i18n/el_GR.po
  contract_sale_generation/i18n/es.po
  contract_sale_generation/i18n/es_MX.po
  contract_sale_generation/i18n/fi.po
  contract_sale_generation/i18n/fr.po
  contract_sale_generation/i18n/gl.po
  contract_sale_generation/i18n/hi_IN.po
  contract_sale_generation/i18n/hr.po
  contract_sale_generation/i18n/hr_HR.po
  contract_sale_generation/i18n/hu.po
  contract_sale_generation/i18n/it.po
  contract_sale_generation/i18n/nl.po
  contract_sale_generation/i18n/nl_NL.po
  contract_sale_generation/i18n/pt.po
  contract_sale_generation/i18n/pt_BR.po
  contract_sale_generation/i18n/pt_PT.po
  contract_sale_generation/i18n/ro.po
  contract_sale_generation/i18n/ru.po
  contract_sale_generation/i18n/sk_SK.po
  contract_sale_generation/i18n/sl.po
  contract_sale_generation/i18n/tr.po
  contract_sale_generation/i18n/tr_TR.po
  contract_sale_generation/i18n/zh_CN.po
  contract_sale_generation/models/__init__.py
  contract_sale_generation/models/abstract_contract.py
  contract_sale_generation/models/contract.py
  contract_sale_generation/models/contract_line.py
  contract_sale_generation/models/sale_order.py
  contract_sale_generation/models/sale_order_line.py
  contract_sale_generation/readme/CONTRIBUTORS.rst
  contract_sale_generation/readme/DESCRIPTION.rst
  contract_sale_generation/readme/USAGE.rst
  contract_sale_generation/static/description/icon.png
  contract_sale_generation/static/description/index.html
  contract_sale_generation/tests/__init__.py
  contract_sale_generation/tests/common.py
  contract_sale_generation/tests/test_contract_sale.py
  contract_sale_generation/views/contract.xml
  setup/contract_sale_generation/odoo/addons/contract_sale_generation
  setup/contract_sale_generation/setup.py
Labels: approved, bot is merging ⏳

#785 ADJ: When generating invoices from the Wizard to create invoices manu…
  contract/tests/__init__.py
  contract/tests/test_contract.py
  contract/tests/test_contract_manually_create_invoice.py
  contract/wizards/contract_manually_create_invoice.py
Labels: approved, bot is merging ⏳

#789 [14.0][FIX] contract: security group_account_invoice from contract_sale to contract
  contract/security/contract_security.xml
  contract_sale/security/contract_security.xml
Labels: bot is merging ⏳

#790 [14.0][FIX] contract: Remove noupdate in mail template data
  contract/__manifest__.py
  contract/data/mail_template.xml
  contract/data/template_mail_notification.xml
Labels: bot is merging ⏳

#772 [14.0][IMP] contract: Remove deprecated domain in onchange
  contract/models/abstract_contract_line.py
  contract/models/contract.py
  contract/tests/test_contract.py
  contract/views/abstract_contract_line.xml
  contract/views/contract.xml
Labels: approved, bot is merging ⏳

#761 [IMP] agreement_maintenance: Adding equipment_id field
  agreement_maintenance/views/agreement_view.xml
Labels: approved, bot is merging ⏳

#793 [FIX] [14.0] Removed external dependencies already defined in Odoo base
  contract/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳
