Repository OCA/contract, pull requests merged in 2022-10, with the labels that each got.

#877 [14.0][FIX] agreement_legal: fix action open agreement
  agreement_legal/models/res_partner.py
Labels: bot is merging ⏳

#881 [14.0][FIX] contract: invoice message create
  contract/models/contract.py
Labels: approved, bot is merging ⏳

#882 [13.0][ADD] agreement_rebate_partner_company_group: New module that apply agreement to all company group members
  agreement_rebate_partner_company_group/README.rst
  agreement_rebate_partner_company_group/__init__.py
  agreement_rebate_partner_company_group/__manifest__.py
  agreement_rebate_partner_company_group/readme/CONTRIBUTORS.rst
  agreement_rebate_partner_company_group/readme/DESCRIPTION.rst
  agreement_rebate_partner_company_group/readme/USAGE.rst
  agreement_rebate_partner_company_group/static/description/icon.png
  agreement_rebate_partner_company_group/static/description/index.html
  agreement_rebate_partner_company_group/tests/__init__.py
  agreement_rebate_partner_company_group/tests/test_agreement_rebate.py
  agreement_rebate_partner_company_group/wizards/__init__.py
  agreement_rebate_partner_company_group/wizards/settlement_create.py
  oca_dependencies.txt
  setup/agreement_rebate_partner_company_group/odoo/addons/agreement_rebate_partner_company_group
  setup/agreement_rebate_partner_company_group/setup.py
Labels: approved, bot is merging ⏳

#883 [14.0][IMP] contract: Set invoice_user_id field with Form() to apply the correct values of other fields.
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: enhancement, approved, bot is merging ⏳

#884 [15.0][IMP] contract: Set invoice_user_id field with Form() to apply the correct values of other fields.
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳

#878 [14.0][IMP] Add link to contract in invoice chatter
  contract/models/contract.py
Labels: approved, ready to merge, bot is merging ⏳

#840 [14.0][FIX] agreement_legal_sale - ignore sale order lines with display_type
  agreement_legal_sale/models/sale_order.py
  agreement_legal_sale/tests/test_sale_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#706 [12.0][ADD] contract_variable_qty_sale_order_line
  contract_variable_qty_sale_order_line/README.rst
  contract_variable_qty_sale_order_line/__init__.py
  contract_variable_qty_sale_order_line/__manifest__.py
  contract_variable_qty_sale_order_line/data/contract_variable_qty_sale_order_line.xml
  contract_variable_qty_sale_order_line/readme/CONTRIBUTORS.rst
  contract_variable_qty_sale_order_line/readme/CREDITS.rst
  contract_variable_qty_sale_order_line/readme/DESCRIPTION.rst
  contract_variable_qty_sale_order_line/readme/USAGE.rst
  contract_variable_qty_sale_order_line/static/description/banner.png
  contract_variable_qty_sale_order_line/static/description/icon.png
  contract_variable_qty_sale_order_line/static/description/index.html
Labels: needs review, approved, ready to merge, bot is merging ⏳
