Repository OCA/contract, pull requests merged in 2022-06, with the labels that each got.

#843 [14.0][IMP] Switch to Github Actions + Promote contract to Production/Stable
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  contract/__manifest__.py
Labels: enhancement

#831 [IMP] contract: Add contract lines entry point for reporting
  contract/models/abstract_contract_line.py
  contract/views/contract.xml
  contract/views/contract_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#809 [14.0][IMP] contract: Make last_date_invoiced optional
  contract/views/contract.xml
Labels: approved, ready to merge, bot is merging ⏳

#561 [13.0][MIG] - migration product_contract
  product_contract/README.rst
  product_contract/__init__.py
  product_contract/__manifest__.py
  product_contract/i18n/de.po
  product_contract/i18n/es.po
  product_contract/i18n/fi.po
  product_contract/i18n/fr.po
  product_contract/i18n/hi_IN.po
  product_contract/i18n/hr.po
  product_contract/i18n/hr_HR.po
  product_contract/i18n/it.po
  product_contract/i18n/nl.po
  product_contract/i18n/nl_NL.po
  product_contract/i18n/product_contract.pot
  product_contract/i18n/pt.po
  product_contract/i18n/pt_BR.po
  product_contract/i18n/ru.po
  product_contract/i18n/tr.po
  product_contract/i18n/tr_TR.po
  product_contract/models/__init__.py
  product_contract/models/contract.py
  product_contract/models/contract_line.py
  product_contract/models/product_template.py
  product_contract/models/res_company.py
  product_contract/models/res_config_settings.py
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/readme/CONTRIBUTORS.rst
  product_contract/readme/DESCRIPTION.rst
  product_contract/readme/USAGE.rst
  product_contract/static/description/icon.png
  product_contract/static/description/index.html
  product_contract/tests/__init__.py
  product_contract/tests/test_product.py
  product_contract/tests/test_sale_order.py
  product_contract/views/contract.xml
  product_contract/views/product_template.xml
  product_contract/views/res_config_settings.xml
  product_contract/views/sale_order.xml
  setup/product_contract/odoo/addons/product_contract
  setup/product_contract/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, stale

#701 [14.0][ENH] agreement: Show active field on list view
  agreement/views/agreement_type.xml
Labels: approved, ready to merge, bot is merging ⏳

#759 [IMP] agreement_serviceprofile: add stage_id view
  agreement_serviceprofile/views/agreement.xml
Labels: approved, ready to merge, bot is merging ⏳

#707 [12.0][FIX] contract: Allow showing contract lines for contracts
  contract/views/contract_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#762 [MIG] agreement_maintenance: Migration to 13.0
  agreement_maintenance/README.rst
  agreement_maintenance/__init__.py
  agreement_maintenance/__manifest__.py
  agreement_maintenance/i18n/agreement_maintenance.pot
  agreement_maintenance/i18n/de.po
  agreement_maintenance/i18n/pt.po
  agreement_maintenance/i18n/pt_BR.po
  agreement_maintenance/i18n/zh_CN.po
  agreement_maintenance/models/__init__.py
  agreement_maintenance/models/agreement.py
  agreement_maintenance/models/agreement_serviceprofile.py
  agreement_maintenance/models/maintenance_equipment.py
  agreement_maintenance/models/maintenance_request.py
  agreement_maintenance/readme/CONFIGURE.rst
  agreement_maintenance/readme/CONTRIBUTORS.rst
  agreement_maintenance/readme/CREDITS.rst
  agreement_maintenance/readme/DESCRIPTION.rst
  agreement_maintenance/readme/USAGE.rst
  agreement_maintenance/static/description/icon.png
  agreement_maintenance/static/description/index.html
  agreement_maintenance/tests/__init__.py
  agreement_maintenance/tests/test_agreement_maintenance.py
  agreement_maintenance/views/agreement_serviceprofile_view.xml
  agreement_maintenance/views/agreement_view.xml
  agreement_maintenance/views/maintenance_equipment_view.xml
  agreement_maintenance/views/maintenance_request_view.xml
  setup/agreement_maintenance/odoo/addons/agreement_maintenance
  setup/agreement_maintenance/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#786 [14.0][ADD] contract_sale_tag
  contract_sale_tag/README.rst
  contract_sale_tag/__init__.py
  contract_sale_tag/__manifest__.py
  contract_sale_tag/models/__init__.py
  contract_sale_tag/models/contract_contract.py
  contract_sale_tag/models/sale_order.py
  contract_sale_tag/readme/CONTRIBUTORS.rst
  contract_sale_tag/readme/DESCRIPTION.rst
  contract_sale_tag/setup/.setuptools-odoo-make-default-ignore
  contract_sale_tag/setup/README
  contract_sale_tag/static/description/icon.png
  contract_sale_tag/static/description/index.html
  contract_sale_tag/tests/__init__.py
  contract_sale_tag/tests/common.py
  contract_sale_tag/tests/test_contract_sale_tag.py
  contract_sale_tag/views/sale_order.xml
  setup/contract_sale_tag/odoo/addons/contract_sale_tag
  setup/contract_sale_tag/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#633 [13.0][ADD] + [MIG] agreement_rebate
  agreement_rebate/README.rst
  agreement_rebate/__init__.py
  agreement_rebate/__manifest__.py
  agreement_rebate/data/agreement_rebate_data.xml
  agreement_rebate/i18n/agreement_rebate.pot
  agreement_rebate/i18n/es.po
  agreement_rebate/migrations/13.0.1.0.0/post-migration.py
  agreement_rebate/migrations/13.0.1.0.0/pre-migration.py
  agreement_rebate/models/__init__.py
  agreement_rebate/models/account_invoice.py
  agreement_rebate/models/agreement.py
  agreement_rebate/models/agreement_rebate_settlement.py
  agreement_rebate/models/agreement_type.py
  agreement_rebate/readme/CONTRIBUTORS.rst
  agreement_rebate/readme/DESCRIPTION.rst
  agreement_rebate/readme/USAGE.rst
  agreement_rebate/security/agreement_rebate_security.xml
  agreement_rebate/security/ir.model.access.csv
  agreement_rebate/static/description/icon.png
  agreement_rebate/static/description/index.html
  agreement_rebate/static/img/agreement_discount_global.png
  agreement_rebate/static/img/agreement_discount_line.png
  agreement_rebate/static/img/agreement_discount_section.png
  agreement_rebate/static/img/agreement_discount_section_rule_match.png
  agreement_rebate/static/img/agreement_rebate_lines_filter.png
  agreement_rebate/static/img/create_settlement_invoices.png
  agreement_rebate/static/img/create_settlements_wizard.png
  agreement_rebate/tests/__init__.py
  agreement_rebate/tests/test_agreement_rebate.py
  agreement_rebate/views/agreement_condition_view.xml
  agreement_rebate/views/agreement_menu_view.xml
  agreement_rebate/views/agreement_rebate_settlement_view.xml
  agreement_rebate/views/agreement_type.xml
  agreement_rebate/views/agreement_view.xml
  agreement_rebate/wizards/__init__.py
  agreement_rebate/wizards/invoice_create.py
  agreement_rebate/wizards/invoice_create_views.xml
  agreement_rebate/wizards/settlement_create.py
  agreement_rebate/wizards/settlement_create_views.xml
  oca_dependencies.txt
  requirements.txt
  setup/agreement_rebate/odoo/addons/agreement_rebate
  setup/agreement_rebate/setup.py
Labels: question, approved, ready to merge, bot is merging ⏳

#812 [14.0][ADD] agreement_tier_validation
  agreement_tier_validation/__init__.py
  agreement_tier_validation/__manifest__.py
  agreement_tier_validation/models/__init__.py
  agreement_tier_validation/models/agreement.py
  agreement_tier_validation/models/tier_definition.py
  agreement_tier_validation/readme/CONFIGURE.rst
  agreement_tier_validation/readme/CONTRIBUTORS.rst
  agreement_tier_validation/readme/DESCRIPTION.rst
  agreement_tier_validation/readme/INSTALL.rst
  agreement_tier_validation/readme/USAGE.rst
  agreement_tier_validation/static/description/icon.png
  agreement_tier_validation/tests/__init__.py
  agreement_tier_validation/tests/test_tier_validation.py
  agreement_tier_validation/views/agreement_view.xml
  setup/agreement_tier_validation/odoo/addons/agreement_tier_validation
  setup/agreement_tier_validation/setup.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#849 [FIX] contract_sale: Good test import
  contract_sale/tests/test_sale_contract.py
Labels: bot is merging ⏳

#847 [MIG] contract_sale_generation: Migration to 15.0
  contract_sale_generation/README.rst
  contract_sale_generation/__init__.py
  contract_sale_generation/__manifest__.py
  contract_sale_generation/data/contract_cron.xml
  contract_sale_generation/i18n/ca.po
  contract_sale_generation/i18n/contract_sale_generation.pot
  contract_sale_generation/i18n/de.po
  contract_sale_generation/i18n/el_GR.po
  contract_sale_generation/i18n/es.po
  contract_sale_generation/i18n/es_AR.po
  contract_sale_generation/i18n/es_MX.po
  contract_sale_generation/i18n/fi.po
  contract_sale_generation/i18n/fr.po
  contract_sale_generation/i18n/gl.po
  contract_sale_generation/i18n/hi_IN.po
  contract_sale_generation/i18n/hr.po
  contract_sale_generation/i18n/hr_HR.po
  contract_sale_generation/i18n/hu.po
  contract_sale_generation/i18n/it.po
  contract_sale_generation/i18n/nl.po
  contract_sale_generation/i18n/nl_NL.po
  contract_sale_generation/i18n/pt.po
  contract_sale_generation/i18n/pt_BR.po
  contract_sale_generation/i18n/pt_PT.po
  contract_sale_generation/i18n/ro.po
  contract_sale_generation/i18n/ru.po
  contract_sale_generation/i18n/sk_SK.po
  contract_sale_generation/i18n/sl.po
  contract_sale_generation/i18n/tr.po
  contract_sale_generation/i18n/tr_TR.po
  contract_sale_generation/i18n/zh_CN.po
  contract_sale_generation/models/__init__.py
  contract_sale_generation/models/abstract_contract.py
  contract_sale_generation/models/contract.py
  contract_sale_generation/models/contract_line.py
  contract_sale_generation/models/sale_order.py
  contract_sale_generation/models/sale_order_line.py
  contract_sale_generation/readme/CONTRIBUTORS.rst
  contract_sale_generation/readme/DESCRIPTION.rst
  contract_sale_generation/readme/USAGE.rst
  contract_sale_generation/static/description/icon.png
  contract_sale_generation/static/description/index.html
  contract_sale_generation/tests/__init__.py
  contract_sale_generation/tests/common.py
  contract_sale_generation/tests/test_contract_sale.py
  contract_sale_generation/tests/test_contract_sale_recurrency.py
  contract_sale_generation/views/contract.xml
  setup/contract_sale_generation/odoo/addons/contract_sale_generation
  setup/contract_sale_generation/setup.py
Labels: approved, bot is merging ⏳

#573 [12.0][Fix] Recurring config missing on order line with product configurator
  product_contract/views/sale_order.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳
