Repository OCA/contract, pull requests merged in 2023-06, with the labels that each got.

#955 [16.0][MIG] contract_sale_generation: Migration to 16.0
  contract_sale_generation/README.rst
  contract_sale_generation/__init__.py
  contract_sale_generation/__manifest__.py
  contract_sale_generation/data/contract_cron.xml
  contract_sale_generation/i18n/ca.po
  contract_sale_generation/i18n/contract_sale_generation.pot
  contract_sale_generation/i18n/de.po
  contract_sale_generation/i18n/el_GR.po
  contract_sale_generation/i18n/es.po
  contract_sale_generation/i18n/es_AR.po
  contract_sale_generation/i18n/es_MX.po
  contract_sale_generation/i18n/fi.po
  contract_sale_generation/i18n/fr.po
  contract_sale_generation/i18n/gl.po
  contract_sale_generation/i18n/hi_IN.po
  contract_sale_generation/i18n/hr.po
  contract_sale_generation/i18n/hr_HR.po
  contract_sale_generation/i18n/hu.po
  contract_sale_generation/i18n/it.po
  contract_sale_generation/i18n/nl.po
  contract_sale_generation/i18n/nl_NL.po
  contract_sale_generation/i18n/pt.po
  contract_sale_generation/i18n/pt_BR.po
  contract_sale_generation/i18n/pt_PT.po
  contract_sale_generation/i18n/ro.po
  contract_sale_generation/i18n/ru.po
  contract_sale_generation/i18n/sk_SK.po
  contract_sale_generation/i18n/sl.po
  contract_sale_generation/i18n/tr.po
  contract_sale_generation/i18n/tr_TR.po
  contract_sale_generation/i18n/zh_CN.po
  contract_sale_generation/models/__init__.py
  contract_sale_generation/models/abstract_contract.py
  contract_sale_generation/models/contract.py
  contract_sale_generation/models/contract_line.py
  contract_sale_generation/models/sale_order.py
  contract_sale_generation/models/sale_order_line.py
  contract_sale_generation/readme/CONTRIBUTORS.rst
  contract_sale_generation/readme/DESCRIPTION.rst
  contract_sale_generation/readme/USAGE.rst
  contract_sale_generation/static/description/icon.png
  contract_sale_generation/static/description/index.html
  contract_sale_generation/tests/__init__.py
  contract_sale_generation/tests/common.py
  contract_sale_generation/tests/test_contract_sale.py
  contract_sale_generation/tests/test_contract_sale_recurrency.py
  contract_sale_generation/views/contract.xml
  setup/contract_sale_generation/odoo/addons/contract_sale_generation
  setup/contract_sale_generation/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#965 [FIX] dependency on 'dateutil' does not appear to be valid
  contract/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#966 [14.0][FIX] contract: Set fixed date to check test correctly.
  contract/tests/test_contract.py
Labels: bot is merging ⏳
