Repository OCA/contract, pull requests merged in 2023-05, with the labels that each got.

#953 [14.0][FIX] contract: show uom only when multi uom is activated
  contract/views/contract.xml
  contract/views/contract_line.xml
  contract/views/contract_template.xml
Labels: bot is merging ⏳

#954 Fix #INVOICEMONTHNAME# for all languages
  contract/i18n/es.po
  contract/models/contract_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#950 [16.0][MIG] contract_invoice_start_end _dates: Migration to 16.0
  contract_invoice_start_end_dates/README.rst
  contract_invoice_start_end_dates/__init__.py
  contract_invoice_start_end_dates/__manifest__.py
  contract_invoice_start_end_dates/i18n/contract_invoice_start_end_dates.pot
  contract_invoice_start_end_dates/i18n/da.po
  contract_invoice_start_end_dates/models/__init__.py
  contract_invoice_start_end_dates/models/contract_line.py
  contract_invoice_start_end_dates/readme/CONTRIBUTORS.rst
  contract_invoice_start_end_dates/readme/DESCRIPTION.rst
  contract_invoice_start_end_dates/static/description/icon.png
  contract_invoice_start_end_dates/static/description/index.html
  contract_invoice_start_end_dates/tests/__init__.py
  contract_invoice_start_end_dates/tests/test_contract_invoice_start_end_dates.py
  setup/contract_invoice_start_end_dates/odoo/addons/contract_invoice_start_end_dates
  setup/contract_invoice_start_end_dates/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#949 [16.0][MIG] contract_sale
  contract_sale/README.rst
  contract_sale/__init__.py
  contract_sale/__manifest__.py
  contract_sale/i18n/contract_sale.pot
  contract_sale/i18n/de.po
  contract_sale/i18n/es.po
  contract_sale/i18n/es_AR.po
  contract_sale/i18n/es_CL.po
  contract_sale/i18n/fr.po
  contract_sale/i18n/gl.po
  contract_sale/i18n/hi_IN.po
  contract_sale/i18n/hr.po
  contract_sale/i18n/hr_HR.po
  contract_sale/i18n/it.po
  contract_sale/i18n/nl.po
  contract_sale/i18n/nl_NL.po
  contract_sale/i18n/pt.po
  contract_sale/i18n/pt_BR.po
  contract_sale/i18n/ro.po
  contract_sale/i18n/ru.po
  contract_sale/i18n/tr.po
  contract_sale/i18n/tr_TR.po
  contract_sale/i18n/zh_CN.po
  contract_sale/readme/CONTRIBUTORS.rst
  contract_sale/readme/DESCRIPTION.rst
  contract_sale/readme/USAGE.rst
  contract_sale/security/contract_security.xml
  contract_sale/security/ir.model.access.csv
  contract_sale/static/description/icon.png
  contract_sale/static/description/index.html
  contract_sale/tests/__init__.py
  contract_sale/tests/test_sale_contract.py
  contract_sale/views/abstract_contract_line.xml
  contract_sale/views/contract.xml
  contract_sale/views/contract_line.xml
  contract_sale/views/contract_template.xml
  contract_sale/views/res_partner_view.xml
  setup/contract_sale/odoo/addons/contract_sale
  setup/contract_sale/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
