Repository OCA/contract, pull requests merged in 2023-01, with the labels that each got.

#894 [15.0][FIX] contract: Switch string > title in buttons
  contract/views/contract_line.xml
Labels: needs review, approved, bot is merging ⏳

#909 [14.0][FIX] contract_mode: fix payment_mode_id domain on supplier form
  contract_payment_mode/views/contract_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#910 [15.0][FIX] contract_mode: fix payment_mode_id domain on supplier form
  contract_payment_mode/views/contract_view.xml
Labels: approved, bot is merging ⏳

#918 [UPD] Copier update
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  agreement/__manifest__.py
  agreement_helpdesk_mgmt/__manifest__.py
  agreement_sale/__manifest__.py
  agreement_serviceprofile/__manifest__.py
  contract/__manifest__.py
  contract/i18n/hr_HR.po
  contract/i18n/it.po
  contract/i18n/tr.po
  contract/i18n/tr_TR.po
  contract_price_revision/__manifest__.py
  contract_sale_generation/__manifest__.py
  contract_sale_invoicing/__manifest__.py
  contract_sale_payment_mode/__manifest__.py
  contract_variable_qty_prorated/__manifest__.py
  contract_variable_qty_timesheet/__manifest__.py
  contract_variable_quantity/__manifest__.py
  product_contract/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#921 [14.0][IMP] agreement_legal: Define warning days cron and filter
  agreement_legal/__manifest__.py
  agreement_legal/data/cron.xml
  agreement_legal/models/agreement.py
  agreement_legal/models/agreement_type.py
  agreement_legal/tests/test_agreement.py
  agreement_legal/views/agreement.xml
  agreement_legal/views/agreement_type.xml
Labels: approved, bot is merging ⏳

#841 [14.0][FIX] contract/contract_sale_generation: Compute correctly the recurring next date after stop()
  contract/models/abstract_contract_line.py
  contract/models/contract.py
  contract/models/contract_line.py
  contract/tests/test_contract.py
  contract_sale_generation/tests/common.py
Labels: bug, enhancement, needs review, approved, bot is merging ⏳
