Repository OCA/contract, pull requests merged in 2023-04, with the labels that each got.

#933 [14.0][MIG] product_contract
  contract/models/contract_line.py
  contract/tests/test_contract.py
  product_contract/README.rst
  product_contract/__init__.py
  product_contract/__manifest__.py
  product_contract/i18n/de.po
  product_contract/i18n/es.po
  product_contract/i18n/fi.po
  product_contract/i18n/fr.po
  product_contract/i18n/hi_IN.po
  product_contract/i18n/hr.po
  product_contract/i18n/hr_HR.po
  product_contract/i18n/it.po
  product_contract/i18n/nl.po
  product_contract/i18n/nl_NL.po
  product_contract/i18n/product_contract.pot
  product_contract/i18n/pt.po
  product_contract/i18n/pt_BR.po
  product_contract/i18n/ru.po
  product_contract/i18n/tr.po
  product_contract/i18n/tr_TR.po
  product_contract/models/__init__.py
  product_contract/models/contract.py
  product_contract/models/contract_line.py
  product_contract/models/product_template.py
  product_contract/models/res_company.py
  product_contract/models/res_config_settings.py
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/readme/CONTRIBUTORS.rst
  product_contract/readme/DESCRIPTION.rst
  product_contract/readme/USAGE.rst
  product_contract/static/description/icon.png
  product_contract/static/description/index.html
  product_contract/tests/__init__.py
  product_contract/tests/test_product.py
  product_contract/tests/test_sale_order.py
  product_contract/views/contract.xml
  product_contract/views/product_template.xml
  product_contract/views/res_config_settings.xml
  product_contract/views/sale_order.xml
  requirements.txt
  setup/product_contract/odoo/addons/product_contract
  setup/product_contract/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#897 [14.0][MIG] contract_queue_job
  contract_queue_job/README.rst
  contract_queue_job/__init__.py
  contract_queue_job/__manifest__.py
  contract_queue_job/data/ir_config_parameter.xml
  contract_queue_job/i18n/contract_queue_job.pot
  contract_queue_job/models/__init__.py
  contract_queue_job/models/contract_contract.py
  contract_queue_job/models/contract_line.py
  contract_queue_job/readme/CONTRIBUTORS.rst
  contract_queue_job/readme/DESCRIPTION.rst
  contract_queue_job/readme/USAGE.rst
  contract_queue_job/static/description/icon.png
  contract_queue_job/static/description/index.html
  contract_queue_job/tests/__init__.py
  contract_queue_job/tests/test_contract_line_queue_job.py
  contract_queue_job/tests/test_contract_queue_job.py
  contract_queue_job/wizards/__init__.py
  contract_queue_job/wizards/contract_manually_create_invoice.py
  contract_queue_job/wizards/contract_manually_create_invoice.xml
  setup/contract_queue_job/odoo/addons/contract_queue_job
  setup/contract_queue_job/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#940 [14.0][FIX] contract: subtotal miscalculated when price_unit displayed with fewer digits than actual value
  contract/models/abstract_contract_line.py
  contract/readme/CONTRIBUTORS.rst
Labels: enhancement, needs review, approved, bot is merging ⏳
