Repository OCA/contract, pull requests merged in 2023-10, with the labels that each got.

#993 [15.0][MIG] contract_variable_qty_timesheet: Migration to version 15.0
  contract_variable_qty_timesheet/README.rst
  contract_variable_qty_timesheet/__init__.py
  contract_variable_qty_timesheet/__manifest__.py
  contract_variable_qty_timesheet/data/contract_line_qty_formula_data.xml
  contract_variable_qty_timesheet/i18n/contract_variable_qty_timesheet.pot
  contract_variable_qty_timesheet/i18n/de.po
  contract_variable_qty_timesheet/i18n/es.po
  contract_variable_qty_timesheet/i18n/fr.po
  contract_variable_qty_timesheet/i18n/it.po
  contract_variable_qty_timesheet/i18n/pt.po
  contract_variable_qty_timesheet/i18n/pt_BR.po
  contract_variable_qty_timesheet/i18n/zh.po
  contract_variable_qty_timesheet/readme/CONTRIBUTORS.rst
  contract_variable_qty_timesheet/readme/DESCRIPTION.rst
  contract_variable_qty_timesheet/readme/USAGE.rst
  contract_variable_qty_timesheet/static/description/icon.png
  contract_variable_qty_timesheet/static/description/index.html
  contract_variable_qty_timesheet/tests/__init__.py
  contract_variable_qty_timesheet/tests/test_contract_variable_qty_timesheet.py
  setup/contract_variable_qty_timesheet/odoo/addons/contract_variable_qty_timesheet
  setup/contract_variable_qty_timesheet/setup.py
Labels: approved, bot is merging ⏳

#996 [16.0][MIG] contract_payment_mode: Migration to version 16.0
  contract_payment_mode/README.rst
  contract_payment_mode/__init__.py
  contract_payment_mode/__manifest__.py
  contract_payment_mode/hooks.py
  contract_payment_mode/i18n/ca.po
  contract_payment_mode/i18n/contract_payment_mode.pot
  contract_payment_mode/i18n/de.po
  contract_payment_mode/i18n/el_GR.po
  contract_payment_mode/i18n/es.po
  contract_payment_mode/i18n/es_AR.po
  contract_payment_mode/i18n/es_MX.po
  contract_payment_mode/i18n/fi.po
  contract_payment_mode/i18n/fr.po
  contract_payment_mode/i18n/gl.po
  contract_payment_mode/i18n/hi_IN.po
  contract_payment_mode/i18n/hr.po
  contract_payment_mode/i18n/hr_HR.po
  contract_payment_mode/i18n/hu.po
  contract_payment_mode/i18n/it.po
  contract_payment_mode/i18n/nl.po
  contract_payment_mode/i18n/pt.po
  contract_payment_mode/i18n/pt_BR.po
  contract_payment_mode/i18n/pt_PT.po
  contract_payment_mode/i18n/ro.po
  contract_payment_mode/i18n/ru.po
  contract_payment_mode/i18n/sk_SK.po
  contract_payment_mode/i18n/sl.po
  contract_payment_mode/i18n/tr.po
  contract_payment_mode/i18n/tr_TR.po
  contract_payment_mode/i18n/zh_CN.po
  contract_payment_mode/models/__init__.py
  contract_payment_mode/models/contract.py
  contract_payment_mode/readme/CONFIGURE.rst
  contract_payment_mode/readme/CONTRIBUTORS.rst
  contract_payment_mode/readme/DESCRIPTION.rst
  contract_payment_mode/readme/USAGE.rst
  contract_payment_mode/static/description/icon.png
  contract_payment_mode/static/description/index.html
  contract_payment_mode/tests/__init__.py
  contract_payment_mode/tests/test_contract_payment.py
  contract_payment_mode/views/contract_view.xml
  setup/contract_payment_mode/odoo/addons/contract_payment_mode
  setup/contract_payment_mode/setup.py
Labels: approved, bot is merging ⏳

#995 [14.0][FIX] contract: Apply some values directly in Form
  contract/__manifest__.py
  contract/models/contract.py
  contract/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#997 [15.0][FIX] contract: Apply some values directly in Form + default name
  contract/__manifest__.py
  contract/models/contract.py
  contract/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#1000 [15.0][FIX] contract: invoice message create
  contract/models/contract.py
Labels: bot is merging ⏳

#1001 [16.0][FIX] contract: invoice message create
  contract/models/contract.py
Labels: bot is merging ⏳

#992 [15.0][MIG] contract_price_revision: Migration to version 15.0
  contract_price_revision/README.rst
  contract_price_revision/__init__.py
  contract_price_revision/__manifest__.py
  contract_price_revision/i18n/contract_price_revision.pot
  contract_price_revision/i18n/es.po
  contract_price_revision/models/__init__.py
  contract_price_revision/models/contract_line.py
  contract_price_revision/readme/CONTRIBUTORS.rst
  contract_price_revision/readme/DESCRIPTION.rst
  contract_price_revision/readme/USAGE.rst
  contract_price_revision/security/ir.model.access.csv
  contract_price_revision/static/description/icon.png
  contract_price_revision/static/description/index.html
  contract_price_revision/tests/__init__.py
  contract_price_revision/tests/test_contract_price_revision.py
  contract_price_revision/views/contract_line.xml
  contract_price_revision/wizards/__init__.py
  contract_price_revision/wizards/contract_price_revision.py
  contract_price_revision/wizards/contract_price_revision_views.xml
  setup/contract_price_revision/odoo/addons/contract_price_revision
  setup/contract_price_revision/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#999 [14.0][MIG] subscription_oca
  setup/subscription_oca/odoo/addons/subscription_oca
  setup/subscription_oca/setup.py
  subscription_oca/README.rst
  subscription_oca/__init__.py
  subscription_oca/__manifest__.py
  subscription_oca/data/ir_cron.xml
  subscription_oca/data/sale_subscription_data.xml
  subscription_oca/i18n/subscription_oca.pot
  subscription_oca/models/__init__.py
  subscription_oca/models/account_move.py
  subscription_oca/models/product_template.py
  subscription_oca/models/res_partner.py
  subscription_oca/models/sale_order.py
  subscription_oca/models/sale_order_line.py
  subscription_oca/models/sale_subscription.py
  subscription_oca/models/sale_subscription_close_reason.py
  subscription_oca/models/sale_subscription_line.py
  subscription_oca/models/sale_subscription_stage.py
  subscription_oca/models/sale_subscription_tag.py
  subscription_oca/models/sale_subscription_template.py
  subscription_oca/readme/CONTRIBUTORS.rst
  subscription_oca/readme/DESCRIPTION.rst
  subscription_oca/readme/ROADMAP.rst
  subscription_oca/readme/USAGE.rst
  subscription_oca/security/ir.model.access.csv
  subscription_oca/static/description/icon.png
  subscription_oca/static/description/index.html
  subscription_oca/static/img/icon.png
  subscription_oca/tests/__init__.py
  subscription_oca/tests/test_subscription_oca.py
  subscription_oca/views/product_template_views.xml
  subscription_oca/views/res_partner_views.xml
  subscription_oca/views/sale_order_views.xml
  subscription_oca/views/sale_subscription_stage_views.xml
  subscription_oca/views/sale_subscription_tag_views.xml
  subscription_oca/views/sale_subscription_template_views.xml
  subscription_oca/views/sale_subscription_views.xml
  subscription_oca/wizard/__init__.py
  subscription_oca/wizard/close_subscription_wizard.py
  subscription_oca/wizard/close_subscription_wizard.xml
Labels: approved, bot is merging ⏳

#1014 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  agreement/i18n/agreement.pot
  agreement/views/agreement.xml
  agreement/views/agreement_type.xml
  agreement_legal/i18n/agreement_legal.pot
  agreement_legal/views/agreement.xml
  agreement_legal/views/agreement_appendix.xml
  agreement_legal/views/agreement_clause.xml
  agreement_legal/views/agreement_recital.xml
  agreement_legal/views/agreement_section.xml
  agreement_serviceprofile/i18n/agreement_serviceprofile.pot
  agreement_serviceprofile/views/agreement_serviceprofile.xml
  contract/i18n/contract.pot
  contract/i18n/hr_HR.po
  contract/i18n/tr_TR.po
  subscription_oca/i18n/subscription_oca.pot
Labels: help wanted, needs review, bot is merging ⏳

#1012 IMP: use group product.group_discount_per_so_line instead of base.gro…
  contract/views/contract.xml
  contract/views/contract_template.xml
Labels: approved, ready to merge, bot is merging ⏳
