Repository OCA/contract, pull requests merged in 2023-11, with the labels that each got.

#974 [IMP ] #INVOICEMONTHNUMBER# #INVOICEYEAR#
  contract/views/contract.xml
Labels: bot is merging ⏳, stale

#1021 [FIX] contract: removed dateutil from dependencies
  contract/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#1002 [15.0][MIG] contract_sale_invoicing: Migration to version 15.0
  contract_sale_invoicing/README.rst
  contract_sale_invoicing/__init__.py
  contract_sale_invoicing/__manifest__.py
  contract_sale_invoicing/i18n/ca.po
  contract_sale_invoicing/i18n/contract_sale_invoicing.pot
  contract_sale_invoicing/i18n/de.po
  contract_sale_invoicing/i18n/el_GR.po
  contract_sale_invoicing/i18n/es.po
  contract_sale_invoicing/i18n/es_CL.po
  contract_sale_invoicing/i18n/es_MX.po
  contract_sale_invoicing/i18n/fi.po
  contract_sale_invoicing/i18n/fr.po
  contract_sale_invoicing/i18n/gl.po
  contract_sale_invoicing/i18n/hi_IN.po
  contract_sale_invoicing/i18n/hr.po
  contract_sale_invoicing/i18n/hr_HR.po
  contract_sale_invoicing/i18n/hu.po
  contract_sale_invoicing/i18n/it.po
  contract_sale_invoicing/i18n/nl.po
  contract_sale_invoicing/i18n/pt.po
  contract_sale_invoicing/i18n/pt_BR.po
  contract_sale_invoicing/i18n/pt_PT.po
  contract_sale_invoicing/i18n/ro.po
  contract_sale_invoicing/i18n/sk_SK.po
  contract_sale_invoicing/i18n/sl.po
  contract_sale_invoicing/i18n/tr.po
  contract_sale_invoicing/i18n/tr_TR.po
  contract_sale_invoicing/i18n/zh.po
  contract_sale_invoicing/i18n/zh_CN.po
  contract_sale_invoicing/models/__init__.py
  contract_sale_invoicing/models/contract.py
  contract_sale_invoicing/readme/CONTRIBUTORS.rst
  contract_sale_invoicing/readme/DESCRIPTION.rst
  contract_sale_invoicing/readme/USAGE.rst
  contract_sale_invoicing/static/description/icon.png
  contract_sale_invoicing/static/description/index.html
  contract_sale_invoicing/tests/__init__.py
  contract_sale_invoicing/tests/test_contract_sale_invoicing.py
  contract_sale_invoicing/views/contract_view.xml
  setup/contract_sale_invoicing/odoo/addons/contract_sale_invoicing
  setup/contract_sale_invoicing/setup.py
Labels: approved, ready to merge, bot is merging ⏳
