Repository OCA/contract, pull requests merged in 2023-02, with the labels that each got.

#919 [15.0][FIX] No contract line and invoices when contract is archived
  contract/models/contract.py
Labels: approved, ready to merge, bot is merging ⏳

#926 [15.0][FIX] contract_payment_mode: set default payment mode by contract type
  contract_payment_mode/models/contract.py
Labels: bot is merging ⏳

#925 [14.0][FIX] contract_payment_mode: set default payment mode by contract type
  contract_payment_mode/models/contract.py
Labels: approved, bot is merging ⏳

#929 [15.0][MIG] agreement_rebate_partner_company_group: Migration to version 15.0
  agreement_rebate_partner_company_group/README.rst
  agreement_rebate_partner_company_group/__init__.py
  agreement_rebate_partner_company_group/__manifest__.py
  agreement_rebate_partner_company_group/i18n/agreement_rebate_partner_company_group.pot
  agreement_rebate_partner_company_group/readme/CONTRIBUTORS.rst
  agreement_rebate_partner_company_group/readme/DESCRIPTION.rst
  agreement_rebate_partner_company_group/readme/USAGE.rst
  agreement_rebate_partner_company_group/static/description/icon.png
  agreement_rebate_partner_company_group/static/description/index.html
  agreement_rebate_partner_company_group/tests/__init__.py
  agreement_rebate_partner_company_group/tests/test_agreement_rebate.py
  agreement_rebate_partner_company_group/wizards/__init__.py
  agreement_rebate_partner_company_group/wizards/settlement_create.py
  setup/agreement_rebate_partner_company_group/odoo/addons/agreement_rebate_partner_company_group
  setup/agreement_rebate_partner_company_group/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳
