Repository OCA/contract, pull requests merged in 2023-09, with the labels that each got.

#987 [14.0][FIX] product_contract: fixes the visibility of the is_contract field in the sales order form
  product_contract/views/sale_order.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#971 [15.0][ADD] subscription_oca
  setup/subscription_oca/odoo/addons/subscription_oca
  setup/subscription_oca/setup.py
  subscription_oca/README.rst
  subscription_oca/__init__.py
  subscription_oca/__manifest__.py
  subscription_oca/data/ir_cron.xml
  subscription_oca/data/sale_subscription_data.xml
  subscription_oca/models/__init__.py
  subscription_oca/models/account_move.py
  subscription_oca/models/product_template.py
  subscription_oca/models/res_partner.py
  subscription_oca/models/sale_order.py
  subscription_oca/models/sale_order_line.py
  subscription_oca/models/sale_subscription.py
  subscription_oca/models/sale_subscription_close_reason.py
  subscription_oca/models/sale_subscription_line.py
  subscription_oca/models/sale_subscription_stage.py
  subscription_oca/models/sale_subscription_tag.py
  subscription_oca/models/sale_subscription_template.py
  subscription_oca/readme/CONTRIBUTORS.rst
  subscription_oca/readme/DESCRIPTION.rst
  subscription_oca/readme/ROADMAP.rst
  subscription_oca/readme/USAGE.rst
  subscription_oca/security/ir.model.access.csv
  subscription_oca/static/description/index.html
  subscription_oca/static/img/icon.png
  subscription_oca/views/product_template_views.xml
  subscription_oca/views/res_partner_views.xml
  subscription_oca/views/sale_order_views.xml
  subscription_oca/views/sale_subscription_stage_views.xml
  subscription_oca/views/sale_subscription_tag_views.xml
  subscription_oca/views/sale_subscription_template_views.xml
  subscription_oca/views/sale_subscription_views.xml
  subscription_oca/wizard/__init__.py
  subscription_oca/wizard/close_subscription_wizard.py
  subscription_oca/wizard/close_subscription_wizard.xml
Labels: needs review, approved, bot is merging ⏳

#991 [15.0][IMP] subscription_oca: Tests, refactoring
  subscription_oca/models/sale_subscription.py
  subscription_oca/readme/CONTRIBUTORS.rst
  subscription_oca/tests/__init__.py
  subscription_oca/tests/test_subscription_oca.py
Labels: bot is merging ⏳
