Repository OCA/contract, pull requests merged in 2023-07, with the labels that each got.

#963 [16.0][FIX] contract_sale: Menu sequence and remove auto install
  contract_sale/__manifest__.py
  contract_sale/views/contract.xml
Labels: approved, ready to merge, bot is merging ⏳

#821 [14.0][FIX] Add check_company=True on contracts and contract lines
  contract/models/abstract_contract.py
  contract/models/contract.py
  contract/models/contract_line.py
  contract/tests/test_contract.py
  contract/views/abstract_contract_line.xml
  contract/views/contract.xml
  contract/views/contract_line.xml
  contract_mandate/models/contract.py
  contract_mandate/views/contract_view.xml
  contract_payment_mode/models/contract.py
  contract_payment_mode/views/contract_view.xml
Labels: bug, bot is merging ⏳, stale

#945 [IMP][14.0] refactor code of product_contract module (make easy inher…
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/tests/test_sale_order.py
  product_contract/views/sale_order.xml
Labels: approved, bot is merging ⏳

#967 [14.0][ADD] contract_split module
  contract_split/README.rst
  contract_split/__init__.py
  contract_split/__manifest__.py
  contract_split/models/__init__.py
  contract_split/models/contract.py
  contract_split/readme/CONTRIBUTORS.rst
  contract_split/readme/DESCRIPTION.rst
  contract_split/readme/ROADMAP.rst
  contract_split/readme/USAGE.rst
  contract_split/security/ir.model.access.csv
  contract_split/tests/__init__.py
  contract_split/tests/test_contract_split.py
  contract_split/views/contract.xml
  contract_split/wizard/__init__.py
  contract_split/wizard/wizard_split_contract.py
  contract_split/wizard/wizard_split_contract.xml
  setup/contract_split/odoo/addons/contract_split
  setup/contract_split/setup.py
Labels: approved, ready to merge, bot is merging ⏳
