Repository OCA/contract, pull requests merged in 2024-01, with the labels that each got.

#1026 [16.0][FIX] No contract line and invoices when contract is archived
  contract/models/contract.py
Labels: bot is merging ⏳

#1019 [16.0][FIX] contract: Usage of analytic distribution
  contract/README.rst
  contract/__manifest__.py
  contract/migrations/16.0.2.0.0/pre-migrate.py
  contract/models/contract_line.py
  contract/static/description/index.html
  contract/views/contract.xml
  contract/views/contract_line.xml
Labels: approved, bot is merging ⏳

#1034 [FIX][14.0] subscription_oca: fix test
  subscription_oca/tests/test_subscription_oca.py
Labels: bot is merging ⏳

#1036 [14.0][IMP] subscription_oca: add maintainers
  subscription_oca/README.rst
  subscription_oca/__manifest__.py
  subscription_oca/static/description/index.html
Labels: bot is merging ⏳

#1028 [14.0] [FIX] subscription_oca: module icon
  subscription_oca/static/img/icon.png
Labels: approved, bot is merging ⏳

#1031 [14.0][IMP] subscription_oca: enable markers to print invoice names
  subscription_oca/models/sale_subscription.py
  subscription_oca/models/sale_subscription_line.py
  subscription_oca/models/sale_subscription_template.py
  subscription_oca/tests/test_subscription_oca.py
  subscription_oca/views/sale_subscription_views.xml
Labels: approved, bot is merging ⏳

#1037 [14.0][IMP] subscription_oca: more invoicing modes
  subscription_oca/models/sale_subscription.py
  subscription_oca/models/sale_subscription_template.py
  subscription_oca/tests/test_subscription_oca.py
  subscription_oca/views/sale_subscription_template_views.xml
  subscription_oca/views/sale_subscription_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1041 [15.0][FIX] contract: Change web_ribbon text to title to make it translatable
  contract/views/contract.xml
  subscription_oca/views/sale_subscription_views.xml
Labels: approved, bot is merging ⏳

#1042 [16.0][FIX] contract: Change web_ribbon text to title to make it translatable
  contract/views/contract.xml
Labels: approved, bot is merging ⏳
