Repository OCA/contract, pull requests merged in 2024-07, with the labels that each got.

#959 [16.0] [MIG] product_contract
  product_contract/README.rst
  product_contract/__init__.py
  product_contract/__manifest__.py
  product_contract/i18n/de.po
  product_contract/i18n/es.po
  product_contract/i18n/fi.po
  product_contract/i18n/fr.po
  product_contract/i18n/hi_IN.po
  product_contract/i18n/hr.po
  product_contract/i18n/hr_HR.po
  product_contract/i18n/it.po
  product_contract/i18n/nl.po
  product_contract/i18n/nl_NL.po
  product_contract/i18n/product_contract.pot
  product_contract/i18n/pt.po
  product_contract/i18n/pt_BR.po
  product_contract/i18n/ru.po
  product_contract/i18n/tr.po
  product_contract/i18n/tr_TR.po
  product_contract/models/__init__.py
  product_contract/models/contract.py
  product_contract/models/contract_line.py
  product_contract/models/product_template.py
  product_contract/models/res_company.py
  product_contract/models/res_config_settings.py
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/readme/CONTRIBUTORS.rst
  product_contract/readme/DESCRIPTION.rst
  product_contract/readme/USAGE.rst
  product_contract/static/description/icon.png
  product_contract/static/description/index.html
  product_contract/tests/__init__.py
  product_contract/tests/test_product.py
  product_contract/tests/test_sale_order.py
  product_contract/views/contract.xml
  product_contract/views/product_template.xml
  product_contract/views/res_config_settings.xml
  product_contract/views/sale_order.xml
  requirements.txt
  setup/product_contract/odoo/addons/product_contract
  setup/product_contract/setup.py
Labels: needs review, migration, bot is merging ⏳

#1099 [17.0][MIG] subscription_oca: Migration to 17.0
  subscription_oca/README.rst
  subscription_oca/__init__.py
  subscription_oca/__manifest__.py
  subscription_oca/data/ir_cron.xml
  subscription_oca/data/sale_subscription_data.xml
  subscription_oca/i18n/es.po
  subscription_oca/i18n/fr.po
  subscription_oca/i18n/it.po
  subscription_oca/i18n/nl.po
  subscription_oca/i18n/subscription_oca.pot
  subscription_oca/models/__init__.py
  subscription_oca/models/account_move.py
  subscription_oca/models/product_template.py
  subscription_oca/models/res_partner.py
  subscription_oca/models/sale_order.py
  subscription_oca/models/sale_order_line.py
  subscription_oca/models/sale_subscription.py
  subscription_oca/models/sale_subscription_close_reason.py
  subscription_oca/models/sale_subscription_line.py
  subscription_oca/models/sale_subscription_stage.py
  subscription_oca/models/sale_subscription_tag.py
  subscription_oca/models/sale_subscription_template.py
  subscription_oca/pyproject.toml
  subscription_oca/readme/CONTRIBUTORS.md
  subscription_oca/readme/DESCRIPTION.md
  subscription_oca/readme/ROADMAP.md
  subscription_oca/readme/USAGE.md
  subscription_oca/security/ir.model.access.csv
  subscription_oca/static/description/icon.png
  subscription_oca/static/description/index.html
  subscription_oca/static/img/icon.png
  subscription_oca/tests/__init__.py
  subscription_oca/tests/test_subscription_oca.py
  subscription_oca/views/product_template_views.xml
  subscription_oca/views/res_partner_views.xml
  subscription_oca/views/sale_order_views.xml
  subscription_oca/views/sale_subscription_stage_views.xml
  subscription_oca/views/sale_subscription_tag_views.xml
  subscription_oca/views/sale_subscription_template_views.xml
  subscription_oca/views/sale_subscription_views.xml
  subscription_oca/wizard/__init__.py
  subscription_oca/wizard/close_subscription_wizard.py
  subscription_oca/wizard/close_subscription_wizard.xml
Labels: approved, bot is merging ⏳

#1023 [15.0][FIX] incorrect inherit res_partner_views
  subscription_oca/views/res_partner_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳, stale
