Repository OCA/contract, pull requests merged in 2024-08, with the labels that each got.

#1119 [17.0][FIX] contract: Fix error when sending contract by email
  contract/models/contract.py
Labels: approved, bot is merging ⏳

#1110 [16.0][MIG] contract_variable_qty_timesheet: Migration to 16.0
  contract_variable_qty_timesheet/README.rst
  contract_variable_qty_timesheet/__init__.py
  contract_variable_qty_timesheet/__manifest__.py
  contract_variable_qty_timesheet/data/contract_line_qty_formula_data.xml
  contract_variable_qty_timesheet/i18n/contract_variable_qty_timesheet.pot
  contract_variable_qty_timesheet/i18n/de.po
  contract_variable_qty_timesheet/i18n/es.po
  contract_variable_qty_timesheet/i18n/fr.po
  contract_variable_qty_timesheet/i18n/it.po
  contract_variable_qty_timesheet/i18n/pt.po
  contract_variable_qty_timesheet/i18n/pt_BR.po
  contract_variable_qty_timesheet/i18n/zh.po
  contract_variable_qty_timesheet/readme/CONTRIBUTORS.rst
  contract_variable_qty_timesheet/readme/DESCRIPTION.rst
  contract_variable_qty_timesheet/readme/USAGE.rst
  contract_variable_qty_timesheet/setup/.setuptools-odoo-make-default-ignore
  contract_variable_qty_timesheet/setup/README
  contract_variable_qty_timesheet/static/description/icon.png
  contract_variable_qty_timesheet/static/description/index.html
  contract_variable_qty_timesheet/tests/__init__.py
  contract_variable_qty_timesheet/tests/test_contract_variable_qty_timesheet.py
  setup/contract_variable_qty_timesheet/odoo/addons/contract_variable_qty_timesheet
  setup/contract_variable_qty_timesheet/setup.py
Labels: approved, bot is merging ⏳

#1070 [16.0][MIG] contract_mandate: Migration to 16.0
  contract_mandate/README.rst
  contract_mandate/__init__.py
  contract_mandate/__manifest__.py
  contract_mandate/i18n/ca.po
  contract_mandate/i18n/contract_mandate.pot
  contract_mandate/i18n/de.po
  contract_mandate/i18n/el_GR.po
  contract_mandate/i18n/es.po
  contract_mandate/i18n/es_AR.po
  contract_mandate/i18n/es_MX.po
  contract_mandate/i18n/fi.po
  contract_mandate/i18n/fr.po
  contract_mandate/i18n/gl.po
  contract_mandate/i18n/hr.po
  contract_mandate/i18n/hr_HR.po
  contract_mandate/i18n/hu.po
  contract_mandate/i18n/it.po
  contract_mandate/i18n/nl.po
  contract_mandate/i18n/pt.po
  contract_mandate/i18n/pt_BR.po
  contract_mandate/i18n/pt_PT.po
  contract_mandate/i18n/ro.po
  contract_mandate/i18n/sk_SK.po
  contract_mandate/i18n/sl.po
  contract_mandate/i18n/zh_CN.po
  contract_mandate/models/__init__.py
  contract_mandate/models/contract.py
  contract_mandate/readme/CONFIGURATION.rst
  contract_mandate/readme/CONTRIBUTORS.rst
  contract_mandate/readme/DESCRIPTION.rst
  contract_mandate/readme/USAGE.rst
  contract_mandate/static/description/icon.png
  contract_mandate/static/description/index.html
  contract_mandate/tests/__init__.py
  contract_mandate/tests/test_contract_mandate.py
  contract_mandate/views/contract_view.xml
  setup/contract_mandate/odoo/addons/contract_mandate
  setup/contract_mandate/setup.py
Labels: needs fixing, approved, migration, ready to merge, bot is merging ⏳

#1106 [17.0][MIG] contract_sale_invoicing: Migration to version 17.0
  contract_sale_invoicing/README.rst
  contract_sale_invoicing/__init__.py
  contract_sale_invoicing/__manifest__.py
  contract_sale_invoicing/i18n/ca.po
  contract_sale_invoicing/i18n/contract_sale_invoicing.pot
  contract_sale_invoicing/i18n/de.po
  contract_sale_invoicing/i18n/el_GR.po
  contract_sale_invoicing/i18n/es.po
  contract_sale_invoicing/i18n/es_CL.po
  contract_sale_invoicing/i18n/es_MX.po
  contract_sale_invoicing/i18n/fi.po
  contract_sale_invoicing/i18n/fr.po
  contract_sale_invoicing/i18n/gl.po
  contract_sale_invoicing/i18n/hi_IN.po
  contract_sale_invoicing/i18n/hr.po
  contract_sale_invoicing/i18n/hr_HR.po
  contract_sale_invoicing/i18n/hu.po
  contract_sale_invoicing/i18n/it.po
  contract_sale_invoicing/i18n/nl.po
  contract_sale_invoicing/i18n/pt.po
  contract_sale_invoicing/i18n/pt_BR.po
  contract_sale_invoicing/i18n/pt_PT.po
  contract_sale_invoicing/i18n/ro.po
  contract_sale_invoicing/i18n/sk_SK.po
  contract_sale_invoicing/i18n/sl.po
  contract_sale_invoicing/i18n/tr.po
  contract_sale_invoicing/i18n/tr_TR.po
  contract_sale_invoicing/i18n/zh.po
  contract_sale_invoicing/i18n/zh_CN.po
  contract_sale_invoicing/models/__init__.py
  contract_sale_invoicing/models/contract.py
  contract_sale_invoicing/pyproject.toml
  contract_sale_invoicing/readme/CONTRIBUTORS.md
  contract_sale_invoicing/readme/DESCRIPTION.md
  contract_sale_invoicing/readme/USAGE.md
  contract_sale_invoicing/static/description/icon.png
  contract_sale_invoicing/static/description/index.html
  contract_sale_invoicing/tests/__init__.py
  contract_sale_invoicing/tests/test_contract_sale_invoicing.py
  contract_sale_invoicing/views/contract_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1104 [17.0][MIG] contract_variable_qty_timesheet: Migration to version 17.0
  contract_variable_qty_timesheet/README.rst
  contract_variable_qty_timesheet/__init__.py
  contract_variable_qty_timesheet/__manifest__.py
  contract_variable_qty_timesheet/data/contract_line_qty_formula_data.xml
  contract_variable_qty_timesheet/i18n/contract_variable_qty_timesheet.pot
  contract_variable_qty_timesheet/i18n/de.po
  contract_variable_qty_timesheet/i18n/es.po
  contract_variable_qty_timesheet/i18n/fr.po
  contract_variable_qty_timesheet/i18n/it.po
  contract_variable_qty_timesheet/i18n/pt.po
  contract_variable_qty_timesheet/i18n/pt_BR.po
  contract_variable_qty_timesheet/i18n/zh.po
  contract_variable_qty_timesheet/pyproject.toml
  contract_variable_qty_timesheet/readme/CONTRIBUTORS.md
  contract_variable_qty_timesheet/readme/DESCRIPTION.md
  contract_variable_qty_timesheet/readme/USAGE.md
  contract_variable_qty_timesheet/setup/.setuptools-odoo-make-default-ignore
  contract_variable_qty_timesheet/setup/README
  contract_variable_qty_timesheet/static/description/icon.png
  contract_variable_qty_timesheet/static/description/index.html
  contract_variable_qty_timesheet/tests/__init__.py
  contract_variable_qty_timesheet/tests/test_contract_variable_qty_timesheet.py
Labels: approved, bot is merging ⏳

#1079 [17.0][FIX] contract: report translations & change structure
  contract/README.rst
  contract/readme/CONTRIBUTORS.md
  contract/report/contract_views.xml
  contract/report/report_contract.xml
  contract/static/description/index.html
Labels: approved, bot is merging ⏳, stale

#1078 [16.0][FIX] contract: report translations & change structure
  contract/README.rst
  contract/readme/CONTRIBUTORS.rst
  contract/report/contract_views.xml
  contract/report/report_contract.xml
  contract/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳, stale

#1105 [17.0][MIG] contract_price_revision: Migration to version 17.0
  contract_price_revision/README.rst
  contract_price_revision/__init__.py
  contract_price_revision/__manifest__.py
  contract_price_revision/i18n/contract_price_revision.pot
  contract_price_revision/i18n/es.po
  contract_price_revision/models/__init__.py
  contract_price_revision/models/contract_line.py
  contract_price_revision/pyproject.toml
  contract_price_revision/readme/CONTRIBUTORS.md
  contract_price_revision/readme/DESCRIPTION.md
  contract_price_revision/readme/USAGE.md
  contract_price_revision/security/ir.model.access.csv
  contract_price_revision/static/description/icon.png
  contract_price_revision/static/description/index.html
  contract_price_revision/tests/__init__.py
  contract_price_revision/tests/test_contract_price_revision.py
  contract_price_revision/views/contract_line.xml
  contract_price_revision/wizards/__init__.py
  contract_price_revision/wizards/contract_price_revision.py
  contract_price_revision/wizards/contract_price_revision_views.xml
Labels: approved, ready to merge, bot is merging ⏳
