Repository OCA/contract, pull requests merged in 2024-02, with the labels that each got.

#1043 [14.0][FIX] subscription_oca: better partner form inheriting
  subscription_oca/readme/CONTRIBUTORS.rst
  subscription_oca/views/res_partner_views.xml
Labels: bot is merging ⏳

#1045 [16.0][OU-FIX] contract: Move migration to post migration
  contract/migrations/16.0.2.0.0/post-migrate.py
Labels: approved

#1046 [14.0][IMP]subscription_oca: search products by name, category and attributes
  subscription_oca/README.rst
  subscription_oca/readme/CONTRIBUTORS.rst
  subscription_oca/static/description/index.html
  subscription_oca/views/sale_subscription_views.xml
Labels: approved, bot is merging ⏳

#917 [FIX]Add ref views on create_invoice action depending on invoices type
  contract/__manifest__.py
  contract/wizards/contract_manually_create_invoice.py
Labels: enhancement, needs review, approved, bot is merging ⏳, stale

#1048 [16.0][FIX] contract: Show discount lines for users with the correct group
  contract/views/abstract_contract_line.xml
  contract/views/contract.xml
  contract/views/contract_line.xml
  contract/views/contract_template.xml
  contract_sale/__manifest__.py
  contract_sale/views/abstract_contract_line.xml
  contract_sale/views/contract.xml
  contract_sale/views/contract_line.xml
  contract_sale/views/contract_template.xml
Labels: approved, bot is merging ⏳

#1050 [16.0][IMP] contract: Protect line recurrrency change
  contract/views/contract.xml
Labels: approved, bot is merging ⏳

#1011 [14.0][FIX] contract: fix domain of payment_term_id field
  contract/models/contract.py
Labels: bot is merging ⏳, stale

#1029 [16.0][MIG] subscription_oca: Migration to 16.0
  setup/subscription_oca/odoo/addons/subscription_oca
  setup/subscription_oca/setup.py
  subscription_oca/README.rst
  subscription_oca/__init__.py
  subscription_oca/__manifest__.py
  subscription_oca/data/ir_cron.xml
  subscription_oca/data/sale_subscription_data.xml
  subscription_oca/i18n/es.po
  subscription_oca/i18n/subscription_oca.pot
  subscription_oca/models/__init__.py
  subscription_oca/models/account_move.py
  subscription_oca/models/product_template.py
  subscription_oca/models/res_partner.py
  subscription_oca/models/sale_order.py
  subscription_oca/models/sale_order_line.py
  subscription_oca/models/sale_subscription.py
  subscription_oca/models/sale_subscription_close_reason.py
  subscription_oca/models/sale_subscription_line.py
  subscription_oca/models/sale_subscription_stage.py
  subscription_oca/models/sale_subscription_tag.py
  subscription_oca/models/sale_subscription_template.py
  subscription_oca/readme/CONTRIBUTORS.rst
  subscription_oca/readme/DESCRIPTION.rst
  subscription_oca/readme/ROADMAP.rst
  subscription_oca/readme/USAGE.rst
  subscription_oca/security/ir.model.access.csv
  subscription_oca/static/description/icon.png
  subscription_oca/static/description/index.html
  subscription_oca/static/img/icon.png
  subscription_oca/tests/__init__.py
  subscription_oca/tests/test_subscription_oca.py
  subscription_oca/views/product_template_views.xml
  subscription_oca/views/res_partner_views.xml
  subscription_oca/views/sale_order_views.xml
  subscription_oca/views/sale_subscription_stage_views.xml
  subscription_oca/views/sale_subscription_tag_views.xml
  subscription_oca/views/sale_subscription_template_views.xml
  subscription_oca/views/sale_subscription_views.xml
  subscription_oca/wizard/__init__.py
  subscription_oca/wizard/close_subscription_wizard.py
  subscription_oca/wizard/close_subscription_wizard.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
