Repository OCA/contract, pull requests merged in 2024-12, with the labels that each got.

#1149 [16][FIX] contract : ignore date constraint for a note
  contract/models/contract_line.py
Labels: approved, bot is merging ⏳

#1150 [17][FIX] contract : ignore date constraint for a note
  contract/models/contract_line.py
Labels: approved, bot is merging ⏳

#1153 [15.0][IMP] contract: Add INVOICEMONTHNAME marker to line description
  contract/README.rst
  contract/models/contract_line.py
  contract/readme/USAGE.rst
  contract/static/description/index.html
  contract/tests/test_contract.py
  contract/views/contract.xml
  contract/views/contract_template.xml
Labels: bot is merging ⏳

#1154 [16.0][IMP] contract: Add INVOICEMONTHNAME marker to line description
  contract/README.rst
  contract/i18n/contract.pot
  contract/i18n/es.po
  contract/models/contract_line.py
  contract/readme/USAGE.rst
  contract/static/description/index.html
  contract/tests/test_contract.py
  contract/views/contract.xml
  contract/views/contract_template.xml
Labels: bot is merging ⏳

#1156 [17.0][IMP] contract: Add INVOICEMONTHNAME marker to line description
  contract/README.rst
  contract/i18n/contract.pot
  contract/i18n/es.po
  contract/models/contract_line.py
  contract/readme/USAGE.md
  contract/static/description/index.html
  contract/tests/test_contract.py
  contract/views/contract.xml
  contract/views/contract_template.xml
Labels: bot is merging ⏳

#1152 [FIX] [16.0] contract: Show contract button on partner when they have contracts too
  contract/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1158 [16.0][FIX] contract: proper condition for auto price
  contract/models/abstract_contract_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1147 [16.0] [MIG] contract_update_last_date_invoiced
  contract_update_last_date_invoiced/README.rst
  contract_update_last_date_invoiced/__init__.py
  contract_update_last_date_invoiced/__manifest__.py
  contract_update_last_date_invoiced/i18n/contract_update_last_date_invoiced.pot
  contract_update_last_date_invoiced/i18n/es.po
  contract_update_last_date_invoiced/i18n/fr.po
  contract_update_last_date_invoiced/models/__init__.py
  contract_update_last_date_invoiced/models/contract_line.py
  contract_update_last_date_invoiced/readme/CONFIGURATION.rst
  contract_update_last_date_invoiced/readme/CONTRIBUTORS.rst
  contract_update_last_date_invoiced/readme/DESCRIPTION.rst
  contract_update_last_date_invoiced/readme/USAGE.rst
  contract_update_last_date_invoiced/security/security.xml
  contract_update_last_date_invoiced/static/description/icon.png
  contract_update_last_date_invoiced/static/description/index.html
  contract_update_last_date_invoiced/views/contract_line.xml
  contract_update_last_date_invoiced/views/contract_views.xml
  contract_update_last_date_invoiced/wizards/__init__.py
  contract_update_last_date_invoiced/wizards/update_last_date_invoiced.py
  contract_update_last_date_invoiced/wizards/update_last_date_invoiced.xml
  setup/contract_update_last_date_invoiced/odoo/addons/contract_update_last_date_invoiced
  setup/contract_update_last_date_invoiced/setup.py
Labels: needs review, approved, bot is merging ⏳

#1163 [15.0][IMP] contract: Use %m instead of %B to obtain month
  contract/models/contract_line.py
Labels: bot is merging ⏳

#1164 [15.0][FIX] product_contract: Fix tests (do not import a test file that does not exist)
  product_contract/tests/__init__.py
Labels: bot is merging ⏳

#1165 [17.0][FIX] contract: link contract instead of move
  contract/models/contract.py
Labels: bot is merging ⏳

#1144 [FIX] product_contract: external dependency name
  product_contract/__manifest__.py
  product_contract/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳
