Repository OCA/contract, pull requests merged in 2024-04, with the labels that each got.

#1069 [16.0][IMP] contract and contract_variable_quantity: improve visual of contract lines
  contract/views/abstract_contract_line.xml
  contract_variable_quantity/views/abstract_contract_line.xml
Labels: approved, bot is merging ⏳

#1071 [16.0][IMP] contract: solve error for last_date_invoiced field
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: approved, bot is merging ⏳

#1075 [17.0][IMP] contract: solve error for last_date_invoiced field
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: bot is merging ⏳

#1077 [16.0] [MIG] contract_queue_job: Migration to 16.0
  contract_queue_job/README.rst
  contract_queue_job/__init__.py
  contract_queue_job/__manifest__.py
  contract_queue_job/data/ir_config_parameter.xml
  contract_queue_job/i18n/contract_queue_job.pot
  contract_queue_job/i18n/es.po
  contract_queue_job/models/__init__.py
  contract_queue_job/models/contract_contract.py
  contract_queue_job/models/contract_line.py
  contract_queue_job/readme/CONTRIBUTORS.rst
  contract_queue_job/readme/DESCRIPTION.rst
  contract_queue_job/readme/USAGE.rst
  contract_queue_job/static/description/icon.png
  contract_queue_job/static/description/index.html
  contract_queue_job/tests/__init__.py
  contract_queue_job/tests/test_contract_line_queue_job.py
  contract_queue_job/tests/test_contract_queue_job.py
  contract_queue_job/wizards/__init__.py
  contract_queue_job/wizards/contract_manually_create_invoice.py
  contract_queue_job/wizards/contract_manually_create_invoice.xml
  setup/contract_queue_job/odoo/addons/contract_queue_job
  setup/contract_queue_job/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1074 [17.0][MIG] contract_sale: Migration to 17.0
  contract_sale/README.rst
  contract_sale/__init__.py
  contract_sale/__manifest__.py
  contract_sale/i18n/ca_ES.po
  contract_sale/i18n/contract_sale.pot
  contract_sale/i18n/de.po
  contract_sale/i18n/es.po
  contract_sale/i18n/es_AR.po
  contract_sale/i18n/es_CL.po
  contract_sale/i18n/fr.po
  contract_sale/i18n/gl.po
  contract_sale/i18n/hi_IN.po
  contract_sale/i18n/hr.po
  contract_sale/i18n/hr_HR.po
  contract_sale/i18n/it.po
  contract_sale/i18n/nl.po
  contract_sale/i18n/nl_NL.po
  contract_sale/i18n/pt.po
  contract_sale/i18n/pt_BR.po
  contract_sale/i18n/ro.po
  contract_sale/i18n/ru.po
  contract_sale/i18n/tr.po
  contract_sale/i18n/tr_TR.po
  contract_sale/i18n/zh_CN.po
  contract_sale/pyproject.toml
  contract_sale/readme/CONTRIBUTORS.md
  contract_sale/readme/DESCRIPTION.md
  contract_sale/readme/USAGE.md
  contract_sale/security/contract_security.xml
  contract_sale/security/ir.model.access.csv
  contract_sale/static/description/icon.png
  contract_sale/static/description/index.html
  contract_sale/tests/__init__.py
  contract_sale/tests/test_sale_contract.py
  contract_sale/views/contract.xml
  contract_sale/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1072 [15.0][FIX] contract: report translations & change structure
  contract/README.rst
  contract/i18n/es.po
  contract/readme/CONTRIBUTORS.rst
  contract/report/contract_views.xml
  contract/report/report_contract.xml
  contract/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳
