Repository OCA/contract, pull requests merged in 2024-03, with the labels that each got.

#1056 [15.0][IMP] contract: Remove buttons from contract lines if recurrence is not per line
  contract/views/contract.xml
Labels: approved, bot is merging ⏳

#1059 [16.0][FIX] contract: Fix modifications layout
  contract/data/template_mail_notification.xml
Labels: approved, bot is merging ⏳

#1054 [16.0][IMP] contract and contract_sale_generation: Add translations
  contract/i18n/es.po
  contract/models/abstract_contract.py
  contract_sale_generation/i18n/es.po
  contract_sale_generation/models/abstract_contract.py
Labels: approved, ready to merge, bot is merging ⏳

#1061 [16.0][IMP] contract: Remove buttons from contract lines if recurrence is not per line
  contract/views/contract.xml
Labels: bot is merging ⏳

#1064 [16.0][IMP] contract: improve visual
  contract/views/abstract_contract_line.xml
Labels: approved, bot is merging ⏳
