Repository OCA/contract, pull requests merged in 2024-05, with the labels that each got.

#1082 [15.0][FIX] contract: solve error for last_date_invoiced field
  contract/models/contract.py
  contract/tests/test_contract.py
Labels: approved, ready to merge, bot is merging ⏳

#1085 [16.0][IMP] contract: remove l10n_generic_coa dependencie
  contract/tests/test_multicompany.py
Labels: approved, bot is merging ⏳

#979 [15.0][MIG] product_contract
  product_contract/README.rst
  product_contract/__init__.py
  product_contract/__manifest__.py
  product_contract/i18n/de.po
  product_contract/i18n/es.po
  product_contract/i18n/fi.po
  product_contract/i18n/fr.po
  product_contract/i18n/hi_IN.po
  product_contract/i18n/hr.po
  product_contract/i18n/hr_HR.po
  product_contract/i18n/it.po
  product_contract/i18n/nl.po
  product_contract/i18n/nl_NL.po
  product_contract/i18n/product_contract.pot
  product_contract/i18n/pt.po
  product_contract/i18n/pt_BR.po
  product_contract/i18n/ru.po
  product_contract/i18n/tr.po
  product_contract/i18n/tr_TR.po
  product_contract/models/__init__.py
  product_contract/models/contract.py
  product_contract/models/contract_line.py
  product_contract/models/product_template.py
  product_contract/models/res_company.py
  product_contract/models/res_config_settings.py
  product_contract/models/sale_order.py
  product_contract/models/sale_order_line.py
  product_contract/readme/CONTRIBUTORS.rst
  product_contract/readme/DESCRIPTION.rst
  product_contract/readme/USAGE.rst
  product_contract/static/description/icon.png
  product_contract/static/description/index.html
  product_contract/tests/__init__.py
  product_contract/tests/test_product.py
  product_contract/tests/test_sale_order.py
  product_contract/views/contract.xml
  product_contract/views/product_template.xml
  product_contract/views/res_config_settings.xml
  product_contract/views/sale_order.xml
  requirements.txt
  setup/product_contract/odoo/addons/product_contract
  setup/product_contract/setup.py
Labels: needs review, migration, bot is merging ⏳, stale
