Repository OCA/contract, pull requests merged in 2025-07, with the labels that each got.

#1212 [18.0][MIG] contract_payment_mode: Migration to 18.0
  contract_payment_mode/README.rst
  contract_payment_mode/__init__.py
  contract_payment_mode/__manifest__.py
  contract_payment_mode/hooks.py
  contract_payment_mode/i18n/ca.po
  contract_payment_mode/i18n/contract_payment_mode.pot
  contract_payment_mode/i18n/de.po
  contract_payment_mode/i18n/el_GR.po
  contract_payment_mode/i18n/es.po
  contract_payment_mode/i18n/es_AR.po
  contract_payment_mode/i18n/es_MX.po
  contract_payment_mode/i18n/fi.po
  contract_payment_mode/i18n/fr.po
  contract_payment_mode/i18n/gl.po
  contract_payment_mode/i18n/hi_IN.po
  contract_payment_mode/i18n/hr.po
  contract_payment_mode/i18n/hr_HR.po
  contract_payment_mode/i18n/hu.po
  contract_payment_mode/i18n/it.po
  contract_payment_mode/i18n/nl.po
  contract_payment_mode/i18n/pt.po
  contract_payment_mode/i18n/pt_BR.po
  contract_payment_mode/i18n/pt_PT.po
  contract_payment_mode/i18n/ro.po
  contract_payment_mode/i18n/ru.po
  contract_payment_mode/i18n/sk_SK.po
  contract_payment_mode/i18n/sl.po
  contract_payment_mode/i18n/tr.po
  contract_payment_mode/i18n/tr_TR.po
  contract_payment_mode/i18n/zh_CN.po
  contract_payment_mode/models/__init__.py
  contract_payment_mode/models/contract.py
  contract_payment_mode/pyproject.toml
  contract_payment_mode/readme/CONFIGURE.md
  contract_payment_mode/readme/CONTRIBUTORS.md
  contract_payment_mode/readme/DESCRIPTION.md
  contract_payment_mode/readme/USAGE.md
  contract_payment_mode/static/description/icon.png
  contract_payment_mode/static/description/index.html
  contract_payment_mode/tests/__init__.py
  contract_payment_mode/tests/test_contract_payment.py
  contract_payment_mode/views/contract_view.xml
Labels: bot is merging ⏳

#1272 [18.0][FIX] product_contract: add missing fields to JS
  product_contract/static/src/js/contract_configurator_controller.esm.js
  product_contract/static/src/js/sale_product_field.esm.js
Labels: approved, bot is merging ⏳

#1138 [18.0][MIG] contract_sale
  contract_sale/README.rst
  contract_sale/__init__.py
  contract_sale/__manifest__.py
  contract_sale/i18n/ca_ES.po
  contract_sale/i18n/contract_sale.pot
  contract_sale/i18n/de.po
  contract_sale/i18n/es.po
  contract_sale/i18n/es_AR.po
  contract_sale/i18n/es_CL.po
  contract_sale/i18n/fr.po
  contract_sale/i18n/gl.po
  contract_sale/i18n/hi_IN.po
  contract_sale/i18n/hr.po
  contract_sale/i18n/hr_HR.po
  contract_sale/i18n/it.po
  contract_sale/i18n/nl.po
  contract_sale/i18n/nl_NL.po
  contract_sale/i18n/pt.po
  contract_sale/i18n/pt_BR.po
  contract_sale/i18n/ro.po
  contract_sale/i18n/ru.po
  contract_sale/i18n/tr.po
  contract_sale/i18n/tr_TR.po
  contract_sale/i18n/zh_CN.po
  contract_sale/pyproject.toml
  contract_sale/readme/CONTRIBUTORS.md
  contract_sale/readme/DESCRIPTION.md
  contract_sale/readme/USAGE.md
  contract_sale/security/contract_security.xml
  contract_sale/security/ir.model.access.csv
  contract_sale/static/description/icon.png
  contract_sale/static/description/index.html
  contract_sale/tests/__init__.py
  contract_sale/tests/test_sale_contract.py
  contract_sale/views/contract.xml
  contract_sale/views/res_partner_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, no stale

#1140 [18.0][MIG] contract_variable_qty_prorated
  contract_variable_qty_prorated/README.rst
  contract_variable_qty_prorated/__init__.py
  contract_variable_qty_prorated/__manifest__.py
  contract_variable_qty_prorated/data/contract_variable_qty_prorated.xml
  contract_variable_qty_prorated/i18n/contract_variable_qty_prorated.pot
  contract_variable_qty_prorated/i18n/fr.po
  contract_variable_qty_prorated/i18n/pt_BR.po
  contract_variable_qty_prorated/models/__init__.py
  contract_variable_qty_prorated/models/contract_line.py
  contract_variable_qty_prorated/pyproject.toml
  contract_variable_qty_prorated/readme/CONTRIBUTORS.md
  contract_variable_qty_prorated/readme/DESCRIPTION.md
  contract_variable_qty_prorated/readme/ROADMAP.md
  contract_variable_qty_prorated/static/description/icon.png
  contract_variable_qty_prorated/static/description/index.html
  contract_variable_qty_prorated/tests/__init__.py
  contract_variable_qty_prorated/tests/test_compute_proprata.py
  contract_variable_qty_prorated/views/contract_template_line.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, no stale

#1145 [18.0][MIG] product_contract_variable_quantity
  product_contract_variable_quantity/README.rst
  product_contract_variable_quantity/__init__.py
  product_contract_variable_quantity/__manifest__.py
  product_contract_variable_quantity/i18n/fr.po
  product_contract_variable_quantity/i18n/it.po
  product_contract_variable_quantity/i18n/product_contract_variable_quantity.pot
  product_contract_variable_quantity/i18n/pt.po
  product_contract_variable_quantity/i18n/pt_BR.po
  product_contract_variable_quantity/models/__init__.py
  product_contract_variable_quantity/models/contract_line.py
  product_contract_variable_quantity/models/product_template.py
  product_contract_variable_quantity/models/sale_order_line.py
  product_contract_variable_quantity/models/sale_order_line_contract_mixin.py
  product_contract_variable_quantity/pyproject.toml
  product_contract_variable_quantity/readme/CONTRIBUTORS.md
  product_contract_variable_quantity/readme/DESCRIPTION.md
  product_contract_variable_quantity/static/description/icon.png
  product_contract_variable_quantity/static/description/index.html
  product_contract_variable_quantity/static/src/js/contract_configurator_controller.esm.js
  product_contract_variable_quantity/static/src/js/sale_product_field.esm.js
  product_contract_variable_quantity/tests/__init__.py
  product_contract_variable_quantity/tests/test_sale_order.py
  product_contract_variable_quantity/views/product_template.xml
  product_contract_variable_quantity/views/sale_order.xml
  product_contract_variable_quantity/wizards/product_contract_configurator.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, no stale
