Repository OCA/contract, pull requests merged in 2025-01, with the labels that each got.

#1169 [17.0][IMP] contract: Use %m instead of %B to obtain month
  contract/models/contract_line.py
Labels: approved, bot is merging ⏳

#1173 [15.0][IMP] contract: Add contract lines entry point for reporting
  contract/models/abstract_contract_line.py
  contract/views/contract.xml
  contract/views/contract_line.xml
Labels: approved

#1174 [16.0][IMP] contract: Add contract lines entry point for reporting
  contract/models/abstract_contract_line.py
  contract/views/contract.xml
  contract/views/contract_line.xml
Labels: approved, bot is merging ⏳

#1175 [17.0][IMP] contract: Add contract lines entry point for reporting
  contract/models/abstract_contract_line.py
  contract/views/contract.xml
  contract/views/contract_line.xml
Labels: approved, bot is merging ⏳

#1177 [17.0][IMP] contract: Terminate contract lines with last_date_invoiced if it is higher than terminate date from wizard
  contract/i18n/contract.pot
  contract/i18n/es.po
  contract/models/contract.py
  contract/tests/test_contract.py
  contract/wizards/contract_contract_terminate.py
  contract/wizards/contract_contract_terminate.xml
Labels: approved, bot is merging ⏳

#1178 [16.0][IMP] contract: Report correction
  contract/report/report_contract.xml
Labels: approved, bot is merging ⏳

#1181 [17.0][IMP] contract: Report correction
  contract/report/report_contract.xml
Labels: bot is merging ⏳

#1187 [17.0][IMP] product_contract: Set description under product name instead of description
  product_contract/README.rst
  product_contract/i18n/es.po
  product_contract/i18n/product_contract.pot
  product_contract/models/sale_order_line.py
  product_contract/readme/CONFIGURE.md
  product_contract/static/description/index.html
  product_contract/static/src/js/sale_product_field.esm.js
  product_contract/views/sale_order.xml
Labels: approved, bot is merging ⏳

#1188 [17.0][FIX] product_contract: Compute date_start and date_end correctly. Make fields computed
  product_contract/README.rst
  product_contract/models/sale_order_line.py
  product_contract/readme/CONTRIBUTORS.md
  product_contract/static/description/index.html
  product_contract/static/src/js/contract_configurator_controller.esm.js
  product_contract/static/src/js/sale_product_field.esm.js
  product_contract/tests/test_sale_order.py
  product_contract/views/sale_order.xml
  product_contract/wizards/product_contract_configurator.py
  product_contract/wizards/product_contract_configurator_views.xml
Labels: approved, bot is merging ⏳
