Repository OCA/contract, pull requests merged in 2025-03, with the labels that each got.

#1201 [16.0][FIX] contract: Post-install test + fallback to load CoA
  contract/tests/test_contract.py
  contract_payment_mode/tests/test_contract_payment.py
  contract_sale_generation/tests/common.py
  contract_variable_quantity/tests/test_contract_variable_quantity.py
  product_contract/tests/test_sale_order.py
  subscription_oca/tests/test_subscription_oca.py
Labels: bot is merging ⏳

#1058 [16.0][IMP] subscription_oca: Various improvements
  subscription_oca/__manifest__.py
  subscription_oca/data/sale_subscription_data.xml
  subscription_oca/models/account_move.py
  subscription_oca/models/sale_subscription.py
  subscription_oca/models/sale_subscription_stage.py
  subscription_oca/static/description/index.html
  subscription_oca/tests/test_subscription_oca.py
  subscription_oca/views/account_move_views.xml
  subscription_oca/wizard/close_subscription_wizard.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1191 [17.0][FIX] product_contract: Compute date_start from the current date instead of date_order
  product_contract/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1185 [17.0][IMP] product_contract: Allow creating sales orders with lines that lack a contract template
  product_contract/models/sale_order.py
  product_contract/tests/test_sale_order.py
Labels: bot is merging ⏳
