Repository OCA/contract, pull requests merged in 2025-09, with the labels that each got.

#1295 [18.0][MIG] contract_analytic_tag: Migration to 18.0
  contract_analytic_tag/README.rst
  contract_analytic_tag/__init__.py
  contract_analytic_tag/__manifest__.py
  contract_analytic_tag/i18n/contract_analytic_tag.pot
  contract_analytic_tag/i18n/es.po
  contract_analytic_tag/i18n/it.po
  contract_analytic_tag/models/__init__.py
  contract_analytic_tag/models/contract_line.py
  contract_analytic_tag/pyproject.toml
  contract_analytic_tag/readme/CONTRIBUTORS.md
  contract_analytic_tag/readme/DESCRIPTION.md
  contract_analytic_tag/static/description/icon.png
  contract_analytic_tag/static/description/index.html
  contract_analytic_tag/tests/__init__.py
  contract_analytic_tag/tests/test_contract_analytic_tag.py
  contract_analytic_tag/views/contract_line_views.xml
  contract_analytic_tag/views/contract_views.xml
Labels: approved, bot is merging ⏳

#1197 [17.0][MIG] contract_analytic_tag: Migration to 17.0
  contract_analytic_tag/README.rst
  contract_analytic_tag/__init__.py
  contract_analytic_tag/__manifest__.py
  contract_analytic_tag/i18n/contract_analytic_tag.pot
  contract_analytic_tag/i18n/es.po
  contract_analytic_tag/i18n/it.po
  contract_analytic_tag/models/__init__.py
  contract_analytic_tag/models/contract_line.py
  contract_analytic_tag/pyproject.toml
  contract_analytic_tag/readme/CONTRIBUTORS.md
  contract_analytic_tag/readme/DESCRIPTION.md
  contract_analytic_tag/static/description/icon.png
  contract_analytic_tag/static/description/index.html
  contract_analytic_tag/tests/__init__.py
  contract_analytic_tag/tests/test_contract_analytic_tag.py
  contract_analytic_tag/views/contract_line_views.xml
  contract_analytic_tag/views/contract_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1236 [18.0][MIG] contract_transmit_method
  contract_transmit_method/README.rst
  contract_transmit_method/__init__.py
  contract_transmit_method/__manifest__.py
  contract_transmit_method/i18n/contract_transmit_method.pot
  contract_transmit_method/i18n/pt_BR.po
  contract_transmit_method/models/__init__.py
  contract_transmit_method/models/contract_contract.py
  contract_transmit_method/models/contract_template.py
  contract_transmit_method/pyproject.toml
  contract_transmit_method/readme/CONTRIBUTORS.md
  contract_transmit_method/readme/DESCRIPTION.md
  contract_transmit_method/static/description/icon.png
  contract_transmit_method/static/description/index.html
  contract_transmit_method/tests/__init__.py
  contract_transmit_method/tests/test_contract.py
  contract_transmit_method/views/contract_contract.xml
  contract_transmit_method/views/contract_template.xml
Labels: needs review, migration, bot is merging ⏳

#1235 [16.0][ADD] contract_sale_invoicing_pricelist
  contract_sale_invoicing_pricelist/README.rst
  contract_sale_invoicing_pricelist/__init__.py
  contract_sale_invoicing_pricelist/__manifest__.py
  contract_sale_invoicing_pricelist/models/__init__.py
  contract_sale_invoicing_pricelist/models/contract.py
  contract_sale_invoicing_pricelist/readme/CONTRIBUTORS.rst
  contract_sale_invoicing_pricelist/readme/CREDITS.rst
  contract_sale_invoicing_pricelist/readme/DESCRIPTION.rst
  contract_sale_invoicing_pricelist/static/description/index.html
  contract_sale_invoicing_pricelist/tests/__init__.py
  contract_sale_invoicing_pricelist/tests/test_contract.py
  setup/contract_sale_invoicing_pricelist/odoo/addons/contract_sale_invoicing_pricelist
  setup/contract_sale_invoicing_pricelist/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1298 [FIX] contract.recurring_create_invoice: Fix singleton error
  contract/models/contract.py
Labels: approved, bot is merging ⏳

#1238 [18.0][MIG] contract_sale_transmit_method
  contract_sale_transmit_method/README.rst
  contract_sale_transmit_method/__init__.py
  contract_sale_transmit_method/__manifest__.py
  contract_sale_transmit_method/models/__init__.py
  contract_sale_transmit_method/models/sale_order.py
  contract_sale_transmit_method/pyproject.toml
  contract_sale_transmit_method/readme/CONTRIBUTORS.md
  contract_sale_transmit_method/readme/DESCRIPTION.md
  contract_sale_transmit_method/static/description/icon.png
  contract_sale_transmit_method/static/description/index.html
  contract_sale_transmit_method/tests/__init__.py
  contract_sale_transmit_method/tests/test_contract_sale_transmit_method.py
Labels: needs review, approved, ready to merge, bot is merging ⏳, no stale

#1301 [16.0][IMP] subscription_oca: add the tag is_move_sent True when the invoice from subscription is sent by email
  subscription_oca/models/sale_subscription.py
  subscription_oca/tests/test_subscription_oca.py
Labels: approved, bot is merging ⏳

#1300 [18.0][MIG] contract_update_last_date_invoiced: Migration to 18
  contract_update_last_date_invoiced/README.rst
  contract_update_last_date_invoiced/__init__.py
  contract_update_last_date_invoiced/__manifest__.py
  contract_update_last_date_invoiced/i18n/contract_update_last_date_invoiced.pot
  contract_update_last_date_invoiced/i18n/es.po
  contract_update_last_date_invoiced/i18n/fr.po
  contract_update_last_date_invoiced/i18n/it.po
  contract_update_last_date_invoiced/models/__init__.py
  contract_update_last_date_invoiced/models/contract_line.py
  contract_update_last_date_invoiced/pyproject.toml
  contract_update_last_date_invoiced/readme/CONFIGURATION.rst
  contract_update_last_date_invoiced/readme/CONTRIBUTORS.md
  contract_update_last_date_invoiced/readme/DESCRIPTION.md
  contract_update_last_date_invoiced/readme/USAGE.md
  contract_update_last_date_invoiced/security/security.xml
  contract_update_last_date_invoiced/static/description/icon.png
  contract_update_last_date_invoiced/static/description/index.html
  contract_update_last_date_invoiced/tests/__init__.py
  contract_update_last_date_invoiced/tests/test_contract_update_last_date_invoiced.py
  contract_update_last_date_invoiced/views/contract_line.xml
  contract_update_last_date_invoiced/views/contract_views.xml
  contract_update_last_date_invoiced/wizards/__init__.py
  contract_update_last_date_invoiced/wizards/update_last_date_invoiced.py
  contract_update_last_date_invoiced/wizards/update_last_date_invoiced.xml
Labels: approved, bot is merging ⏳

#1308 [17.0][FIX] contract_sale_invoicing: Proper flag visualization
  contract_sale_invoicing/views/contract_view.xml
Labels: approved, bot is merging ⏳

#1309 [18.0][FIX] contract_sale_invoicing: Proper flag visualization
  contract_sale_invoicing/views/contract_view.xml
Labels: approved, bot is merging ⏳
