Repository OCA/contract, pull requests merged in 2025-06, with the labels that each got.

#1239 [17.0][MIG] contract_queue_job
  contract_queue_job/README.rst
  contract_queue_job/__init__.py
  contract_queue_job/__manifest__.py
  contract_queue_job/data/ir_config_parameter.xml
  contract_queue_job/i18n/contract_queue_job.pot
  contract_queue_job/i18n/es.po
  contract_queue_job/i18n/it.po
  contract_queue_job/models/__init__.py
  contract_queue_job/models/contract_contract.py
  contract_queue_job/models/contract_line.py
  contract_queue_job/pyproject.toml
  contract_queue_job/readme/CONTRIBUTORS.md
  contract_queue_job/readme/DESCRIPTION.md
  contract_queue_job/readme/USAGE.md
  contract_queue_job/static/description/icon.png
  contract_queue_job/static/description/index.html
  contract_queue_job/tests/__init__.py
  contract_queue_job/tests/test_contract_line_queue_job.py
  contract_queue_job/tests/test_contract_queue_job.py
  contract_queue_job/wizards/__init__.py
  contract_queue_job/wizards/contract_manually_create_invoice.py
  contract_queue_job/wizards/contract_manually_create_invoice.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1167 [16.0] FIX subscription_oca in multi company + allow to invoice with recurring_next_date before today
  subscription_oca/models/sale_subscription.py
  subscription_oca/tests/test_subscription_oca.py
  subscription_oca/views/sale_subscription_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1225 [18.0][MIG] contract_forecast
  contract_forecast/README.rst
  contract_forecast/__init__.py
  contract_forecast/__manifest__.py
  contract_forecast/data/queue_job_channel.xml
  contract_forecast/data/queue_job_functions.xml
  contract_forecast/hooks.py
  contract_forecast/i18n/contract_forecast.pot
  contract_forecast/i18n/de.po
  contract_forecast/i18n/es.po
  contract_forecast/i18n/fr.po
  contract_forecast/i18n/it.po
  contract_forecast/i18n/pt.po
  contract_forecast/i18n/pt_BR.po
  contract_forecast/models/__init__.py
  contract_forecast/models/contract.py
  contract_forecast/models/contract_line.py
  contract_forecast/models/contract_line_forecast_period.py
  contract_forecast/models/res_company.py
  contract_forecast/models/res_config_settings.py
  contract_forecast/pyproject.toml
  contract_forecast/readme/CONFIGURE.md
  contract_forecast/readme/CONTRIBUTORS.md
  contract_forecast/readme/DESCRIPTION.md
  contract_forecast/readme/USAGE.md
  contract_forecast/security/contract_line_forecast_period.xml
  contract_forecast/static/description/icon.png
  contract_forecast/static/description/index.html
  contract_forecast/tests/__init__.py
  contract_forecast/tests/test_contract_line_forecast_period.py
  contract_forecast/views/contract.xml
  contract_forecast/views/contract_line_forecast_period.xml
  contract_forecast/views/res_config_settings.xml
  contract_forecast_variable_quantity/README.rst
  contract_forecast_variable_quantity/__init__.py
  contract_forecast_variable_quantity/__manifest__.py
  contract_forecast_variable_quantity/models/__init__.py
  contract_forecast_variable_quantity/models/contract_line.py
  contract_forecast_variable_quantity/pyproject.toml
  contract_forecast_variable_quantity/readme/CONTRIBUTORS.md
  contract_forecast_variable_quantity/readme/DESCRIPTION.md
  contract_forecast_variable_quantity/static/description/icon.png
  contract_forecast_variable_quantity/static/description/index.html
  contract_forecast_variable_quantity/tests/__init__.py
  contract_forecast_variable_quantity/tests/test_contract.py
Labels: needs review, approved, migration, bot is merging ⏳, no stale

#1254 [18.0][FIX] contract line successor: use parent.is_auto_renew to avoid EvalError in column_invisible
  contract/static/src/js/contract_portal_tour.esm.js
  contract_line_successor/models/__init__.py
  contract_line_successor/models/contract_template.py
  contract_line_successor/tests/test_contract.py
  contract_line_successor/views/contract_template.xml
  product_contract/static/src/js/contract_configurator_controller.esm.js
  product_contract/static/src/js/sale_product_field.esm.js
Labels: approved, ready to merge, bot is merging ⏳
